### ISSUE TITLE
Auto-populate and open the "Set default Device" when opening systray menu (See picture)

### ISSUE THREAD

**Issue by syper** [irzyxa/Volume2#103]
To make it even more handy and to avoid some clicks in order to see the current setup and ease the cange of input, it could be interesting to auto-populate and open the "Set default Device" when onpening the systray menu:

See example on the picture below:

![image](https://user-images.githubusercontent.com/6415455/87883269-1d611800-c9fe-11ea-868d-6c2da59b3251.png)

It's a quick way to visually see what is the active device and be able to change it without need to open a sub-menu!

**Comment by irzyxa** [comment]
Done.
![image](https://user-images.githubusercontent.com/5119360/87985173-d0577180-cae3-11ea-8556-49cab70a752e.png)

**Comment by irzyxa** [comment]
Added

**Comment by syper** [comment]
Fantastic, looks awesome!
