### ISSUE TITLE
L\R balance works incorrectly

### ISSUE THREAD

**Issue by hitriy** [irzyxa/Volume2#108]
Single click on the app icon in system tray calls a menu with volume and L\R balance. 
Balance always moved to the left. Changing balance doesn't do anything with balance, but lowering down volume.

![2020-10-22 11_03_49-](https://user-images.githubusercontent.com/10556875/96843753-5b376780-1457-11eb-8ef0-50c40ee2aa9f.png)

 - Windows version: 10(2004)
 - Volume² version: 1.1.6.426

**Comment by alexandr-irza** [comment]
What device do you control? Some devices do not support changing balance.

**Comment by hitriy** [comment]
It's Jabra evolve 40 uc stereo usb headset.

**Comment by hitriy** [comment]
Switched to Realtek speakers, the app works correctly. 
Seems it's vendor specific issue, not sure if need to be fixed
