### ISSUE TITLE
Volume2 randomly closes, unanticipated settings change

### ISSUE THREAD

**Issue by nollinvoyd** [irzyxa/Volume2#109]
Occasionally, for some reason, Volume2 shuts down, and I have to manually restart it, but today, something else odd happened.

I once again experienced the Volume2 shut down, evidenced by no screen edge response, but when I went to restart it from the shortcut, nothing happened.  No volume control.

It turns out Volume2 was actually still running, but the Screen edge option "Change mouse volume when move along screen's edge, had become mysteriously unchecked.  I haven't had the need to go into the settings in quite a while, and Volume2 was working normally today, until suddenly, it wasn't.

After I re-enabled the option, it's resumed normal operation.

 - Windows 10 (1909)
 - Volume² v1.1.6, build 426 (02.08.2020)

**Comment by alexandr-irza** [comment]
Try to use option as described here
[https://github.com/irzyxa/Volume2/wiki/FAQ/_edit#5-stops-working-after-awhile](url)
