### ISSUE TITLE
Host the binary files also here on github

### ISSUE THREAD

**Issue by c33s** [irzyxa/Volume2#110]
**Describe the solution you'd like**
it's quite cumbersome to download your awesome program, all the sites needs tons of javascript from different domains and cookies, no easy possibilty to simply fetch it with wget.

![image](https://user-images.githubusercontent.com/649209/99202061-37ddaf00-27ae-11eb-91d4-4efab0025a92.png)

for example pressing download on google drive results in a `The page isn’t redirecting properly`

by hosting it on github you would allow easy downloads with wget

**Comment by irzyxa** [comment]
There are not only google links. volumesqr.at.ua contains direct links. I cannot use github for storing only executable files without sources.
https://irzyxa.blogspot.com/p/downloads.html

**Comment by c33s** [comment]
@irzyxa why not also hosting here? yandex, onedrive and google really needs much cross domain permissions and volumesqr.at.ua leads to server not found

![image](https://user-images.githubusercontent.com/649209/103142726-887aed00-4708-11eb-80df-16685b66d4c7.png)
![image](https://user-images.githubusercontent.com/649209/103142732-b6f8c800-4708-11eb-9951-8eb075538162.png)

**Comment by irzyxa** [comment]
Here direct links
https://volumesqr.at.ua/Beta/Volume2_1_1_6.zip
https://volumesqr.at.ua/Beta/Setup_Volume2_1_1_6.zip

**Comment by c33s** [comment]
as i said from my location i get a server not found error
