### ISSUE TITLE
Command-line options doesn't change volume

### ISSUE THREAD

**Issue by Saxtus** [irzyxa/Volume2#113]
**Describe the bug**

Command-line options /mute /unmute /inc xx and /dec xx don't do anything.
Last version that was working as expected: v1.1.6.413
Until v1.1.6.423 the commands changed the Windows default device instead of the Audio device selected at Volume2 main settings.
Since v1.1.6.426, I am getting the error as appears on the following screenshot (screenshot is from v1.1.6.428).

**Screenshots**
https://i.imgur.com/SMrPTkF.png

**Desktop (please complete the following information):**
 - Windows version: 10 (2004)
 - Volume² version: 1.1.6.428

**Additional context**
Maybe related to the bug I've reported about the webserver that has similar issues: #114

**Comment by irzyxa** [comment]
Fixed, will be available in version 1.1.7.429
