### ISSUE TITLE
Webserver commands don't change volume

### ISSUE THREAD

**Issue by Saxtus** [irzyxa/Volume2#114]
**Describe the bug**
Using any of the volume commands doesn't do anything, like for example /volume?up or /volume?mute
Last version that was working as expected: 1.1.6.413

**Desktop (please complete the following information):**
 - Windows version: 10 (2004)
 - Volume² version: 1.1.6.428

**Additional context**
Maybe related to the bug I've reported about the command-line options that have similar issues: #113

**Comment by irzyxa** [comment]
Here example of web client. So, now you should use POST method.
[WebClient.zip](https://github.com/irzyxa/Volume2/files/5759272/WebClient.zip)

**Comment by Saxtus** [comment]
The example mentioned by Volume² doesn't use post, that's why I assumed it uses GET from previous versions.

**Comment by irzyxa** [comment]
@Saxtus ye, previous version was different. But than I have started developing Android client and saw that it will be better to use correct methods for set data POST, for get data GET.
