### ISSUE TITLE
No installation

### ISSUE THREAD

**Issue by VenusGirl** [irzyxa/Volume2#116]
**Describe the bug**

**Screenshots**
![Volume2 Installer](https://user-images.githubusercontent.com/53147200/103434679-2d855080-4c48-11eb-9c4c-df7221a358c8.png)

**Desktop**
 - Windows version: [e.g. 7, 8, 10(1909) more later]
 - Volume² version: [e.g. 1.1.6.411~428]

**Additional context**
The directory cannot be created because of the corresponding characters in the picture, so it cannot be installed with Setup_Volume2_1_1_6_428.exe. You must either have the option to skip the installation or rename the skin in English.

**Comment by irzyxa** [comment]
Fixed, will be available in version 1.1.7.429

**Comment by irzyxa** [comment]
It was cryic 'c' in 'colored'
