### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by mjsheen** [irzyxa/Volume2#118]
**Describe the bug**
Install failure. Same bug had occurred in the previous version as well.
Couldn't create directory 'Dark panel nolored peaks'.

My suspicion was the unique alphabet name might be something Windows did not allow. 
I can use portable version without problem. I find it strange that it is differently named as "Dark panel fiery peaks" instead of "nolored peaks" in the portable version.

Your app is life saving as I had been having problem with Windows being confused what to link with the hardware volume control on the keyboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/76853816/103447482-3d944300-4ccf-11eb-9af3-1c06ec10223f.png)

**Desktop (please complete the following information):**
 - Windows version: Windows 10 19042.685
 - Volume² version: 1.1.6.428

**Additional context**

**Comment by irzyxa** [comment]
Fixed, please redownload installer
