### ISSUE TITLE
OSD stops working, icon becomes unresponsive

### ISSUE THREAD

**Issue by baz357** [irzyxa/Volume2#119]
Sometimes, Volume²'s OSD stops working and the taskbar icon becomes unresponsive. Volume changes are still possible and the icon shows the changed volume, but there's no OSD anymore and right-clicking the taskbar icon won't work anymore. (And I just found out that when I then double-click the icon, an empty Options window is opened.) If this happens, I can only kill Volume2 in the Windows task manager and start it again.

I had this happen in versions .415, .426 and now .428 but found no way to reproduce it reliably. The issue might have something to do with locking Windows and logging back in later on, I recall two times when it showed up in this context. (And I use Volume²'s 'mute on lock' feature, which is probably not a factor, but I wanted to mention it anyway.)

And - if I recall correctly - it only happens after Windows has been running for at least 48 hours.

- Windows 10 Home 2004 19041.685
- Volume² 1.1.6.428

Thank you for Volume²!

**Comment by irzyxa** [comment]
Could you send your profile folder?
https://github.com/irzyxa/Volume2/wiki/FAQ#4-where-is-configini-located

**Comment by baz357** [comment]
Sure thing. Here's the Config.ini:

`
;Warning! Editing this file, can cause Volume² to stop work
[Languages]
LangFileName=English.lng
LangName=English (US)

[UserVariables]
ImmediateHideVolumeControl=0
ExKatMouseClasses=TRichViewEdit
ExKatMouseExcludeClasses=Windows.UI.Core.CoreWindow
ExKatMouseScrollCount=1
UseRemoteServer=0
RemoteServerPort=22222
RemoteServerUdpPort=22221
DelayBeforePlaySound=500
DelayBeforeRestartMouseHook=-1
UseAutoRestartHooks=0
DelayBeforeHideHint=2500
DelayBeforeHideEdgeWnd=5000
LowLevelHooksTimeout=10000
LowLevelShortKeys=Pause,"Win + 0","Win + 1","Win + 2","Win + 3","Win + 4","Win + 5","Win + 6","Win + 7","Win + 8","Win + 9","Win + Up","Win + Down","Win + Left","Win + Right",F12
ExScrollObjects=ActualTools_MultiMonitorTaskbar,DockBackgroundClassTrueStretch,DFTaskbar*
DefaultDeviceRole=-1
DetectActiveMonitorMethod=1
UseLockDevicesVolume=0
DevicesSort=1
AutoClosePeakMeter=0

[MouseMoveVolumeControl]
EdgeLeft=0
EdgeRight=1
EdgeTop=0
EdgeBottom=1
EdgeHintInfo=%D: %V%
EdgeShowToolTip=0
UseMoveWatch=1
TypeControlEdge=1
MoveStartStep=100
MoveStep=50
UseDisableSoundMiddleButton=0
EdgeZoneWidth=8
EdgeShowOSD=1
ShowEdgeWindow=1
ShowEdgeWindowWhenVolumeChanged=0
EdgeBackColorOn=-16711936
EdgeBackColorOff=-65536
EdgeDisableWhenFullScreen=0

[System]
UseAlternativeMouseWheel=0
UseInverse=0
AskOnExit=0
ShowStandartRegulator=1
UseLongClick=0
RestoreSystemVolume=0
SystemVolume=30
SystemMute=0
SoundName=No sound
UseAutoUpdate=1
UseBetaUpdate=1
NotifyUsb=1
NotifyCD=1
NotifyBright=1
NotifyVolume=1
SystemShowBaloonHint=1
NotifyVolumeType=0

[Main]
VolSpeed=20
AltDeviceScrollKey=0
UseAltDevice=0
MethodControl=0
ChangeVolumeFileName=
ChangeVolumeOption=0
AltChangeVolumeFileName=
AltChangeVolumeOption=0
OffVolumeControlOnFullScreen=0
DisableHotKeysInFullScreen=0
AutoRun=1
ScheduleAutoRun=0
DeviceId=~
AltDeviceId=NO
UnMuteOnVolumeChange=0
UnMuteOnVolumeIncrease=0

[MouseActions]
UseDisableVolume=0
DisableVolumeMouseKey=0
DisableVolumeKey=0
ScrollObject=1
UseMouseScroll=1
UseDisableSoundMiddleButton=0
LeftMouseEvent=1
DblLeftMouseEvent=4
MidleMouseEvent=3
DisableMouseScrollInFullScreen=0
ScrollKey=0
UseScrollKey=0
MuteOnZeroVolume=0
EnableSoudAfteChangeVol=0

[OSD]
OsdHintInfo=%D: %V%
OSDStepWidth=30
OSDSpaceWidth=1
OSDBorderSize=2
OSDContourSize=2
OSDProgressFadeSteps=25
OSDProgressShowSteps=100
OSDBorderColor=-16777216
OSDTextCountorColor=-16777216
OSDFontColorOn=-16711936
OSDFontColorOff=-16776961
OSDBackColorOn=-16711936
OSDBackColorOff=-16776961
OSDBackColorOnTo=-16711936
TrackBarColorOnFrom=-5308791
TrackBarColorOnTo=-1
TrackBarColorOffFrom=-47546
TrackBarColorOffTo=-1
OSDBackColorOffTo=-16776961
OSDFontSize=32
OSDShowTime=600
OSDTextBorder=1
OSDTextDelineate=1
OSDTextBlocks=1
OSDTextVisible=1
OSDFontName=Verdana
OSDFontBold=0
OSDFontItalic=0
OSDStyle=1
OSDOrientation=0
OsdWhileDisplaing=0
CurOSDHeight=100
CurOSDWidth=500
OSDTrackBarHeight=100
OSDTrackBarWidth=27
UseLabelOSDTrackBar=0
UseOSDTrackBarMousePosition=1
OSDTransparent=0
OSDShowFullBlocks=0
UseOSD=1
OSDSkinName=Acer Blue Digits
DisableOSDInFullScreen=0
MonitorIndex=0
OSDStretchPercent=100
OSDPosition=1
OSDPositionLeft=50
OSDPositionTop=90
OSDStretchPercent2=100
OSDPosition2=1
OSDPositionLeft2=50
OSDPositionTop2=90

[InterfaceColors]
COLOR_BORDER=14342874
COLOR_SELECTED=15263976
COLOR_BACKGROUND=16777215

[Skins]
SkinName=Volume2 Default Light

[AdvSettings]
UseBalloonHint=0
BalloonHintInfo=%D: %V%
StyleHint=1

[SystemTray]
ShowTrayHintOnVolumeChange=0

[TrayVolumeControl]
TimeAutoHideVolumeControl=5000
`


And here are this year's errors, "07.01.2021 14:18" was when I logged back into Windows and when the Volume² bug showed up again:

`
Fr 01.01.2021 10:19:23	ERROR	Error RefreshVistaDevicesList: Some operation could not be performed because the system is out of resources. Close some windows and try again.
Fr 01.01.2021 10:19:24	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Fr 01.01.2021 10:24:56	ERROR	Error RefreshVistaDevicesList: Some operation could not be performed because the system is out of resources. Close some windows and try again.
Fr 01.01.2021 10:29:51	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:36:30	ERROR	Error RefreshVistaDevicesList: Some operation could not be performed because the system is out of resources. Close some windows and try again.
Mo 04.01.2021 15:46:42	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:46:43	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:47:03	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 15:47:03	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 15:47:56	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:47:56	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:48:19	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 15:48:19	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 15:56:03	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:56:03	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:56:26	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 15:56:26	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 15:59:51	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 15:59:51	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 16:12:05	ERROR	MainShow: Canvas does not allow drawing
Mo 04.01.2021 16:12:18	ERROR	MainShow: Canvas does not allow drawing
Mo 04.01.2021 16:12:58	ERROR	MainShow: Canvas does not allow drawing
Mo 04.01.2021 16:54:07	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 16:54:07	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 16:57:57	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 16:57:57	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 16:58:49	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 16:58:49	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:00:12	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:00:12	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:00:35	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:00:35	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:05:03	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:05:04	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:06:30	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:06:30	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:07:29	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:07:29	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:07:52	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:07:53	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:08:48	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:08:48	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:09:11	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:09:11	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:21:28	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:21:28	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:21:51	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:21:51	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 17:35:07	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 17:35:07	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 18:13:35	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 18:13:36	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 18:13:50	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 18:13:50	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 18:57:09	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 18:57:09	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:00:26	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:00:26	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:01:19	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:01:19	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:01:22	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:01:22	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:02:14	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:02:14	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:05:02	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:05:02	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:06:28	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:06:28	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:15:21	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:15:41	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:15:42	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:15:47	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:15:47	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:16:10	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:16:11	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Mo 04.01.2021 19:35:34	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:35:35	ERROR	Error RefreshVistaDevicesList: Out of system resources
Mo 04.01.2021 19:36:20	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:21	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:22	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:22	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:23	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:23	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:23	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:23	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:26	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:36:26	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:31	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:31	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:31	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:31	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:32	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:34	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:38:37	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:45:20	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:45:20	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:45:20	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 19:45:20	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:32:57	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:13	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:13	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:13	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:13	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:13	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:14	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:59	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:59	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:59	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:33:59	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:34:43	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:42:50	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:42:50	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:42:50	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:42:50	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:55:06	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:55:06	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:55:06	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:55:06	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:56:44	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:56:45	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:56:45	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:56:45	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:33	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:35	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:35	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:35	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 20:57:40	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:05:26	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:05:26	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:05:26	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:05:26	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:05:34	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:07:48	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:07:48	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:07:48	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Mo 04.01.2021 21:07:48	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 13:45:36	ERROR	Error RefreshVistaDevicesList: Some operation could not be performed because the system is out of resources. Close some windows and try again.
Do 07.01.2021 13:45:56	ERROR	Error RefreshVistaDevicesList: Some operation could not be performed because the system is out of resources. Close some windows and try again.
Do 07.01.2021 13:45:56	ERROR	Error RefreshVistaDevicesList: Falscher Parameter.

Do 07.01.2021 14:18:13	ERROR	Error RefreshVistaDevicesList: Out of system resources
Do 07.01.2021 14:18:14	ERROR	Error RefreshVistaDevicesList: Out of system resources
Do 07.01.2021 14:18:36	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:18:36	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:18:36	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:18:36	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:04	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:05	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:05	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:06	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:08	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:08	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:08	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:08	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:09	ERROR	ShowEdgeWindow: Canvas does not allow drawing
Do 07.01.2021 14:19:12	ERROR	MainShow: Klasse ist nicht vorhanden
`

**Comment by baz357** [comment]
And here's Schedules.ini (I didn't find a way how to attach files here):

;Warning! Editing this file, can cause Volume² to stop work
[quiet at night]
Enable=1
Action=0
Period=5
Second=3
Minute=30
Hour=0
Day=10
Month=7
Year=2020
ProgramName=
RunIfNotStarted=0
MessageName=
MessageSound=
AfterRunProgramName=
Volume=0
Mute=0
DeviceID=DFX Speakers (DFX Audio Enhancer)
Balance=18
Brightness=0
StartingAt=00:00:00
UseTimeRange=0
EndingAt=23:59:59
NumOfRuns=1
LimitRuns=0
Mon=1
Tue=1
Wed=1
Thu=1
Fri=1
Sat=1
Sun=1

[quiet when locking PC]
Enable=1
Action=0
Period=10
Second=9
Minute=34
Hour=13
Day=10
Month=7
Year=2020
ProgramName=
RunIfNotStarted=0
MessageName=
MessageSound=
AfterRunProgramName=
Volume=0
Mute=0
DeviceID=DFX Speakers (DFX Audio Enhancer)
Balance=18
Brightness=0
StartingAt=00:00:00
UseTimeRange=0
EndingAt=23:59:59
NumOfRuns=1
LimitRuns=0
Mon=1
Tue=1
Wed=1
Thu=1
Fri=1
Sat=1
Sun=1

[reboot message]
Enable=0
Action=2
Period=11
Second=32
Minute=51
Hour=13
Day=10
Month=7
Year=2020
ProgramName=
RunIfNotStarted=0
MessageName=volume was reduced to 0 (Volume2)
MessageSound=
AfterRunProgramName=
Volume=0
Mute=0
DeviceID=DFX Speakers (DFX Audio Enhancer)
Balance=18
Brightness=0
StartingAt=00:00:00
UseTimeRange=0
EndingAt=23:59:59
NumOfRuns=1
LimitRuns=0
Mon=1
Tue=1
Wed=1
Thu=1
Fri=1
Sat=1
Sun=1

**Comment by TReKiE** [comment]
Same issue here, although I believe I know part of the issue, and suspect it's related to #112.  When the OSD won't come up, nor the main window, the GDI objects for the process are at 9,999 (default Windows config is 10,000 GDI objects per process and after that it won't allow any more).

So there does seem to be some sort of GDI leak, but I'm not sure what triggers it unfortunately.  It is a new problem though, as I've been using Volume² for years with no issue.

**Comment by baz357** [comment]
> Same issue here, although I believe I know part of the issue, and suspect it's related to #112. When the OSD won't come up, nor the main window, the GDI objects for the process are at 9,999 (default Windows config is 10,000 GDI objects per process and after that it won't allow any more).

Thanks for sharing, that sounds plausible.

**Comment by shonay** [comment]
I also have this same issue for the past few versions now.
It seems to occur almost every day when I come back to work in the morning.

I have a laptop, with a second monitor attached to it via HDMI.
When I leave at the end of the day, I lock my laptop so that it's on the login screen, close the lid and turn off the monitor. My laptop is NOT set to go to sleep so that it remains online all the time. When I return to work, I switch on my HDMI monitor and then open the lid and then login to the computer and the issue always occurs (No OSD displayed, and icon unresponsive to mouse clicks).

Sometimes however when I forget to lock the laptop and switch off the monitor then the OSD works fine the next day. But not always.

**Comment by zeroarst** [comment]
I can reproduce the problem by putting my PC into sleep and wake it up. The icon is stall in task tray. But my "screen edge" settings do not work until I double-click the app to reopen it. 
Windows 10 64 bit
3 monitors.

**Comment by irzyxa** [comment]
Maybe for someone this will fix the issue
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by shonay** [comment]
> Maybe for someone this will fix the issue
> https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

Already have this setting checked. Unfortunately the problem still occurs. Thanks though.

**Comment by TReKiE** [comment]
> Maybe for someone this will fix the issue
> https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

The hook was still working as the volume still changes (using rotating mouse wheel over taskbar), it's just the OSD that won't appear or the options window.
However, I did have this enabled initially, so at the time, I disabled the reload hook option to see if the hook was causing the issue.  It didn't seem to change anything.

Also, since posting here before, I moved back to 1.1.6.411 and the problem went away.

**Comment by baz357** [comment]
> Also, since posting here before, I moved back to 1.1.6.411 and the problem went away.

If that's the case it would be great if that version could be put (back) on https://irzyxa.blogspot.com/p/downloads.html - I want it! :)

**Comment by TReKiE** [comment]
1.1.6.411 was the first version I found in my Downloads folder, but I've since collected more.  I've uploaded these if you want to try yourself:
[Version 1.1.6.411](https://f.trekie.net/Volume2/Setup_Volume2_1_1_6_411.zip)
[Version 1.1.6.413](https://f.trekie.net/Volume2/Setup_Volume2_1_1_6_413.zip)
[Version 1.1.6.415](https://f.trekie.net/Volume2/Setup_Volume2_1_1_6_415.zip)
[Version 1.1.6.426](https://f.trekie.net/Volume2/Setup_Volume2_1_1_6_426.zip)

I recommend uploading the zip to VirusTotal to verify it's the original (Details tab, first submit date).

**Comment by irzyxa** [comment]
@TReKiE Thank you. Here all versions:
[Versions 1.1.6.xxx](https://drive.google.com/drive/folders/0B01PgcpQil--MnRRYS1hY2JqeE0)

**Comment by irzyxa** [comment]
@TReKiE Could you try some versions after 411? I looked at code and did not see any changes that could breaking down OSD.

**Comment by irzyxa** [comment]
What OSD type did you use?

**Comment by shonay** [comment]
Not sure about @TReKiE, but I use the Acer Blue Digits OSD.

**Comment by baz357** [comment]
> Not sure about @TReKiE, but I use the Acer Blue Digits OSD.

Acer Blue Digits here too.

**Comment by TReKiE** [comment]
I'm only using Windows 10 v2, but I don't think the OSD itself is the cause.  As I mentioned above, I believe it's the GDI objects running out, and I've got a solid repro of that now in #127.

**Comment by baz357** [comment]
> I'm only using Windows 10 v2, but I don't think the OSD itself is the cause. As I mentioned above, I believe it's the GDI objects running out, and I've got a solid repro of that now in #127.

I agree. I've been running .431 since it has been released - and with a different OSD for testing purposes - and the GDI count is increasing and increasing there too... and without ever interacting with the icon.

And, by the way, that #127 is _the_ most impressive bug report I ever saw! 🥇 :)

**Comment by irzyxa** [comment]
Could someone do screenshot of task manager with column GDI Objects when this issue happens?

**Comment by irzyxa** [comment]
Maybe this happens on laptops only?

**Comment by baz357** [comment]
> Could someone do screenshot of task manager with column GDI Objects when this issue happens?

I can't now/today since I killed Volume² 30 minutes ago when it had reached a GDI count of 9999 (and the OSD stopped working). Its GDI count is ~1500 now.

> Maybe this happens on laptops only?

Hmm... shonay wrote that he uses a laptop, I'm a laptop user too.

**Comment by shonay** [comment]
FYI, it happens on my home **desktop** too.
However I did notice that it's only occurring on my computers that have multi-monitor setups.

I loaded version 1.1.6.411 (as suggested from earlier posts) and all is working well.
Only thing I really miss from the newer version is the ability to resize the OSD.

**Comment by irzyxa** [comment]
Okay, I reproduced it. It happens when you connect/disconnect audio devices(I think all of you use monitors with audio devices)

**Comment by baz357** [comment]
> Okay, I reproduced it. It happens when you connect/disconnect audio devices(I think all of you use monitors with audio devices)

I don't use such a monitor, but I do use a secondary audio device, and something regarding audio devices also happens when the energy saving options turn off the screens.

**Comment by irzyxa** [comment]
Fixed, problem was in tray menu, when a new device is connected, Volume2 reloads all devices to the tray menu but it was handle leak on menu draw.

**Comment by baz357** [comment]
> Fixed, problem was in tray menu, when a new device is connected, Volume2 reloads all devices to the tray menu but it was handle leak on menu draw.

Ah, okay. Looking forward to the next beta release! :)

**Comment by irzyxa** [comment]
Fixed version 1.1.7.432

**Comment by baz357** [comment]
> Fixed version 1.1.7.432

https://irzyxa.blogspot.com/p/downloads.html says that https://volumesqr.at.ua/Beta/Setup_Volume2_1_1_7.zip now should contain build 432 but it still contains 431.

**Comment by irzyxa** [comment]
@baz357 Are you sure? I downloaded it and there is 1.1.7.432
![image](https://user-images.githubusercontent.com/5119360/106056162-09a61500-60f7-11eb-8546-51fa9a88ce1f.png)

**Comment by baz357** [comment]
> @baz357 Are you sure? I downloaded it and there is 1.1.7.432

I've tried it several times, always got 431. After you replied I've tried a different browser and got 432. Weird! :)

Thank you!

**Comment by TReKiE** [comment]
Not that this at all surprising, but I can confirm no issues here after a few days here with 1.1.7.432.  Thanks @irzyxa for jumping on that issue so quickly.  Also thanks to everyone who contributed, I'm pleased to know I'm not the only Volume² fan 😄
