### ISSUE TITLE
Can't increase volume using F12 key

### ISSUE THREAD

**Issue by maxvre** [irzyxa/Volume2#12]
Using version 1.1.5.361 (28.12.2015)

Using Windows 10 enterprise 64bit and a qwerty mac keyboard.
Assigning F12 key as 'volume up' doesn't work.
Worked ok using previous version.

**Comment by irzyxa** [comment]
You need to change Config.ini file 
[UserVariables]
LowLevelShortKeys=Pause,"Win + 0","Win + 1","Win + 2","Win + 3","Win + 4","Win + 5","Win + 6","Win + 7","Win + 8","Win + 9","Win + Up","Win + Down","Win + Left","Win + Right",F12
Add F12 at the end of string LowLevelShortKeys
