### ISSUE TITLE
 Jiangmin Trojan.Generic.xqar on Virustotal a false positive?

### ISSUE THREAD

**Issue by Purecontent** [irzyxa/Volume2#123]
Just downloaded version 1.1.6.428 and got this from Virustotal I have used V2 for years and really love it, just making sure the newest version is still safe.
![F1X7rVRbZW](https://user-images.githubusercontent.com/54852025/105156020-38265d80-5b03-11eb-8eef-4017ae77ba26.jpg)

**Comment by irzyxa** [comment]
Sometimes antiviruses can react on Volume2 because it sets keyboard and mouse hooks to control volume.

**Comment by Purecontent** [comment]
understood and thanks for reply
