### ISSUE TITLE
Volume cap setting

### ISSUE THREAD

**Issue by ThisIsABug** [irzyxa/Volume2#125]
Could you implement a (per device) volume cap setting?

Some of my audio devices allow me to set a pretty high volume which can end in short but shocking moments while switching sound output. I must admit this problem is purely selfmade because the devices remember their last set volume just fine. But I imagine it would be a great addition to your already awesome program.

**Comment by irzyxa** [comment]
You can do this in existing version. Just add Task on changing device as shown on screenshot
![image](https://user-images.githubusercontent.com/5119360/105411084-935b6b80-5c3b-11eb-88de-bec7b66d8f32.png)

**Comment by ThisIsABug** [comment]
Oh. That's a great solution too. Thank you.
