### ISSUE TITLE
Include third device 

### ISSUE THREAD

**Issue by tiagogl** [irzyxa/Volume2#126]
I have Sound Blaster Z and in order to use Headset, my Home Theather sound still playing and I need always mute on remote control. I can mute using software but need be directly on SPDIF-OUT but I have DTS sound and SPDIF-OUT is not my main and second device.
So the solution will be include a third device or option to mute any play device on my PC using a hotkey.

Thanks a lot

**Comment by irzyxa** [comment]
I think I know how to extend functionality to resolve your issue. I will add to Hotkeys a new  Action - 'Run task', and than you can configure task 'Mute On for Device' and set on hotkey.

**Comment by tiagogl** [comment]
GREAT. Thanks a lot. Let me know and I will test!

**Comment by irzyxa** [comment]
@tiagogl You can try a new version.
https://irzyxa.blogspot.com/p/downloads.html

**Comment by tiagogl** [comment]
Where I need create this task?

**Comment by tiagogl** [comment]
I found:
I can mute but not unmute :/. If I press again still muted
![image](https://user-images.githubusercontent.com/36077491/105423705-ce05d980-5c24-11eb-9fd8-b519fcc93622.png)

**Comment by irzyxa** [comment]
For unmute you have to use anothe task and combination

**Comment by irzyxa** [comment]
Okay, I can add one more state Mute, Unmute and Toggle and this will fix your situation.

**Comment by tiagogl** [comment]
> Okay, I can add one more state Mute, Unmute and Toggle and this will fix your situation.

Thanks a lot. I fixed using you advice but have this feature will be nice too
![image](https://user-images.githubusercontent.com/36077491/105518018-8465cf00-5cb6-11eb-84b4-f13c82c376de.png)

**Comment by irzyxa** [comment]
@tiagogl I updated files, please redownload them.

**Comment by tiagogl** [comment]
Now if Perfect!

https://user-images.githubusercontent.com/36077491/105703193-a2684500-5eeb-11eb-839a-7d29c370a83e.mp4
