### ISSUE TITLE
GDI object leak on right-click context menu

### ISSUE THREAD

**Issue by TReKiE** [irzyxa/Volume2#127]
Right-clicking the Volume² notification area icon creates more GDI objects and never releases them.  Eventually, the per-process limit (10,000) is reached and the OSD will no longer come up, nor will Options, nor the built-in volume control UI (Standard regulator) function.  The results are identical to the issues reported in #119.

**Repro**
1. Open Task Manager
2. Go to the Details (Win8+) or Processes tab
3. Right-click on one of the columns, choose Select columns
4. Find the GDI objects, select it and choose OK
5. Click on the GDI objects field to sort
6. Run Volume² if not already started
7. Go to the notification area (system tray) and right-click on the Volume² icon
8. Observe GDI objects for Volume2.exe rising
9. Repeat right-clicking and watch the GDI objects value

![](https://i.imgur.com/yaGRKUg.gif)

Since no one wants to spend all day clicking, here is [an AutoHotKey script](https://f.trekie.net/Volume2/RightClick.ahk) to continuously right-click the icon, and [an executable version ](https://f.trekie.net/Volume2/RightClick.exe) if you don't have AutoHotKey handy.  The script will begin immediately right-clicking upon startup.

Here's a sped up GIF showing this.  It takes about 2 minutes normally:
![](https://i.imgur.com/vtBgzBr.gif)

Although the volume control part still works, since only two new GDI objects can be created, it can't create the OSD, the built-in volume control UI, nor the Options, as shown here:
![](https://i.imgur.com/5JhefHw.png)

 - Windows version: 10 (20H2 and 21296 [current insider dev])
 - Volume² version: 1.1.6.411 and 1.1.6.428

**Additional**
[GDIView](https://www.nirsoft.net/utils/gdi_handles.html) shows the vast majority of these objects as being bitmaps.  Also, out of curiosity, why are 1,461 objects used at startup when nothing is on the screen?  All the parts of the UI that the user interacts with are created later.  I suspect this leak at initialization may be part of it as well.

**Comment by irzyxa** [comment]
Fixed version 1.1.7.432
