### ISSUE TITLE
Greek Language update

### ISSUE THREAD

**Issue by geonetor** [irzyxa/Volume2#128]
**Describe the bug**
I have updated the Greek language file to v.1.1.6.428 and i am sending it to you.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version: 10(2009)
 - Volume² version: 1.1.6.428

**Additional context**

[Greece.zip](https://github.com/irzyxa/Volume2/files/5865757/Greece.zip)

**Comment by irzyxa** [comment]
Updated
