### ISSUE TITLE
Make "no change" the default option when installing Volume2

### ISSUE THREAD

**Issue by baz357** [irzyxa/Volume2#136]
Every time I install a new Volume2 version, I have to remember to click the "no change" options. I don't want to change anything because I have set up Volume2 exactly how I like it (using all the wonderful options). :) I'm sure that's the case for most people most of the time, so wouldn't it make sense to have the installer _standard_ be "change nothing"?

**Comment by irzyxa** [comment]
Version 1.1.7.438
