### ISSUE TITLE
[request] Run schedule when Volume2 start up

### ISSUE THREAD

**Issue by nhantrn** [irzyxa/Volume2#14]
I have a couple software tools that I schedule in Volume2 to start at night around ~9pm. It works great, but the problem is that when I restart Windows,I have to manually open those tools.
It would be great if Volume2 could process its schedule at program start up. Now it should only start those entry in the schedule if it matches a time interval specify in each entry.

**Comment by irzyxa** [comment]
This option already exist. When you create Task in Schedules, select Run: On Start.

**Comment by nhantrn** [comment]
I know that option, but I want it to run on start **only** after a point in time. I have this dimmer ultility that I only want to run at night. I hope you that make sense?

**Comment by irzyxa** [comment]
Do you want this option?(enabled Start/End time)
https://dl.dropboxusercontent.com/u/25826071/pictures/1.1.4/OnStartTime.png

**Comment by nhantrn** [comment]
Yes! but that is disabled on mine.

**Comment by irzyxa** [comment]
This is photoshop :)

**Comment by nhantrn** [comment]
Ok, this works for me:
![2016-02-01_010929](https://cloud.githubusercontent.com/assets/3202654/12712993/fefab4bc-c880-11e5-85dc-1fe4ea8833c7.jpg)
