### ISSUE TITLE
Add command line option to toggle mute 

### ISSUE THREAD

**Issue by Saxtus** [irzyxa/Volume2#142]
Right now, there are command-line options to mute or unmute the selected device (although it does it to the default device instead - bug #130).
Please add a new option to toggle mute the selected device instead.

**Comment by irzyxa** [comment]
But this options is available:
![image](https://user-images.githubusercontent.com/5119360/113390707-ee77b000-939a-11eb-9c32-8a3093328b86.png)

**Comment by Saxtus** [comment]
Oh so sorry, my bad. Please disregard this feature then.
I can't wait to be able to finally use it when the other bug gets fixed.

**Comment by rp1231** [comment]
Where can I access the window with the commands that you have attached?
I can't seem to find it.

**Comment by irzyxa** [comment]
You can use it like this: volume2.exe /?
