### ISSUE TITLE
Put Windows into sleep and wake it up, the screen edge stop working until click/open the app again.

### ISSUE THREAD

**Issue by zeroarst** [irzyxa/Volume2#145]
**Describe the bug**
I like screen edge feature, my settings allow me to change volume by scrolling up/down on the screen edge.
However, there is a little issue that annoys me. When put Windows into sleep and wake it up, the screen edge stop working. I have to click/open the app icon on the notification area to make it works again. Wondering if this can be fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1834837/120442776-53667b00-c3c9-11eb-8bd6-69df917e6a1c.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/1834837/120443133-b0623100-c3c9-11eb-9945-1711fd629c9d.png)
![image](https://user-images.githubusercontent.com/1834837/120443189-bce68980-c3c9-11eb-80e2-eab989189b08.png)

**Additional context**

**Comment by irzyxa** [comment]
I think it should help: https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by irzyxa** [comment]
I think it should help: https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by baz357** [comment]
@zeroarst: Did this fix it for you?

**Comment by zeroarst** [comment]
Yes. It works for me.
