### ISSUE TITLE
Flyout takeover

### ISSUE THREAD

**Issue by ninuola** [irzyxa/Volume2#147]
**Describe the bug**
The app hides the default Windows flyout when it is running, even when you turn off "Show OSD" in the OSD settings. Previously, it did it sometimes but a restart would fix it. Now it prevents it from showing all the time.

**Screenshots**
No screenshot.

**Desktop (please complete the following information):**
 - Windows version: 10 21H1
 - Volume² version: 1.1.7.434

**Additional context**
To provide more context about the issue... When I am gaming and I control the volume from my headset when the Volume2 app IS NOT running, a Windows volume flyout will pop up and show the volume adjustments. When the Volume2 app IS running, it prevents the Windows flyout from popping up, and because the Volume2 flyout doesn't show when I am running a game, I won't see any volume adjustment.
I think the app should allow you to choose between the default Windows flyout (pop up) or its own flyout. Turning off "Show OSD" should probably be the way to implement this.

**Comment by irzyxa** [comment]
Please try to disable hotkeys. There is option 'Disable in full screen
applications'.

вс, 19 сент. 2021 г., 20:50 ninuola ***@***.***>:

**Comment by ninuola** [comment]
Thank you. Removing the hotkeys fixed the issue for me. I guess I will have to live without the hotkeys, which is fine with me. Thanks again.
