### ISSUE TITLE
Multiple alternate devices/Keybinds for arbitrary devices

### ISSUE THREAD

**Issue by slidedrum** [irzyxa/Volume2#148]
I would like to have multiple alternate devices, or the ability to set keybinds to change the volume of specific devices.

I have separate playback devices for streaming.  I have a virtual audio cable for computer/music/voice/other/unused, with computer as the default device. Then they all then get mirrored into my headphones.  I have set up Volume2 so that my volume up and down keys change the volume of my headphones as the alternate device, which works perfectly!  This is what it looks like 
![image](https://user-images.githubusercontent.com/14340641/134510702-c2ac4168-7b83-4637-83be-a9a995c72a63.png)

I would like to be able to set a hotkey to for example, increase the volume of the music playback device, or the game sound.  And this is how I would imagine it looking: 
![image](https://user-images.githubusercontent.com/14340641/134511256-389878ab-ba3e-4f93-88ae-627f36e779af.png)

Thank you for your time and consideration :)

**Comment by irzyxa** [comment]
Done. Version 1.1.7.436
