### ISSUE TITLE
Better "Manage Devices" alternatives than the dropdown menu.

### ISSUE THREAD

**Issue by hellishvictor** [irzyxa/Volume2#150]
Hi, with the present "Manage Devices" dropdown menu is really a tedious task when there's several devices, because the menu disappear after of enable or disable each one:
![Volume²](https://user-images.githubusercontent.com/34694956/139576513-c389f2ad-d69c-4214-8140-9909bddefffb.gif)

It would better that after of select "Manage Devices", it display a float window where they can be activated or disabled:
![Volume²](https://user-images.githubusercontent.com/34694956/139576039-3638b0b6-3987-42f6-950f-c695457c47a0.jpg)

Another good alternative will be add it on the section "Main" on the Volume²'s "Options" window:
![Volume²_](https://user-images.githubusercontent.com/34694956/139577969-48a196a5-4913-47c6-88b6-cd1435cb53f8.jpg)

Cheers.

**Comment by irzyxa** [comment]
I think it will be better to extend existing window(it can be opened by clicking on icon or via hotkeys)
![image](https://user-images.githubusercontent.com/5119360/139960696-46c5f990-3339-43bc-becd-86bd289fd0e2.png)

**Comment by irzyxa** [comment]
Version 1.1.7.438

**Comment by hellishvictor** [comment]
> Version 1.1.7.438

Hi, I have tested the update and it behaves the same way, the menu still dissapears after a selection... there's is any changes done related to this?
Cheers.

**Comment by irzyxa** [comment]
I went the way I described, just extended existing device manager.
Unfortunately menu cannot stay visible after click.

**Comment by hellishvictor** [comment]
Well, thank you anyway.

**Comment by hellishvictor** [comment]
> I went the way I described, just extended existing device manager. 
Hi, today I had noticed one thing; I actually mean the expandable menu "Manage Devices" (where are the devices that will be shown/enabled on the Set Default Devices list), not the "Set Default Device" section (on which you did an outstanding job, btw).

> Unfortunately menu cannot stay visible after click.
That is why I suggested a float window, just like the one used on the extended "Set Default Device" float window.
![139576039-3638b0b6-3987-42f6-950f-c695457c47a0](https://user-images.githubusercontent.com/34694956/144769240-35f3aeaa-7d81-4020-ad53-92c609995adc.jpg)

**Comment by irzyxa** [comment]
But you can use right mouse button and Enable/Disable devices. What is you using case? And why do you need to do this so fast?
