### ISSUE TITLE
Does Not Change Windows Default Device

### ISSUE THREAD

**Issue by EagleEyeYT56** [irzyxa/Volume2#151]
I saw another issue opened about this but I didn't know what they were talking about. Whenever I set Windows Default as Alternative Audio Device, it can't control the volume anymore. When I set it back to the main audio device, it can control it again. I tried using my headset to test it the Alternative Audio Device was the problem, it was able to control it easily. I'm using HeSuVi to give off 7.1 channels on my stereo headset. I want Volume² to control my headset volume since I can't control it when using the surround sound. Once I disconnect the headset, I want Volume² to control the default audio device which is set to the alternative audio device. A response ASAP would help, thanks!

![image](https://user-images.githubusercontent.com/40913104/141216146-d71c6de3-d4e7-462b-9dbc-8d4745c8c252.png)

**Desktop** 
 - Windows 11 Pro Insider Preview 22494.1000
 - Volume² version: 1.1.6.428

**Additional context**

**Comment by irzyxa** [comment]
I think you misunderstood how alternative device works. You can use it to control 2 devices at the same time, the first one just use scroll and alternative - Alt key + scroll. In your case you should just set Windows Default for main device and it will work as you described.

**Comment by EagleEyeYT56** [comment]
OHHHHHHHHHHHHHHHH
Thanks for the brief explanation. Is there a FAQ or a TL;DR in case confusion happens again?
Also while playing an FPS game, it still scrolls and adjusts volume when you look down. Is there a way for Volume² to not overlap a full-screen application? I know you can disable Volume² when fullscreened, but I'm using HeSuVi, and volume control is not a thing.

**Comment by EagleEyeYT56** [comment]
Thanks for the response irzyxa! Is there a TL;DR or a FAQ in case confusion happens again?

**Comment by Galixte** [comment]
> Thanks for the response irzyxa! Is there a TL;DR or a FAQ in case confusion happens again?

https://github.com/irzyxa/Volume2/wiki
