### ISSUE TITLE
tray icon wrong volume display

### ISSUE THREAD

**Issue by Slope86** [irzyxa/Volume2#153]
[bug video](https://youtu.be/06onQUvl-30)
Windows version: 19043.1348 (21H1)
Volume² version: 1.1.7.437 & 1.1.6.428

**Comment by irzyxa** [comment]
Could you send me your Config.ini?

**Comment by Slope123** [comment]
Sure, [Config_ini](https://anonfiles.com/FfjfHcW6u9/Config_ini)

**Comment by irzyxa** [comment]
Sis you change any program components? Another question: what mouse do you use? And could you record vide with Volume2 settings?

**Comment by Slope123** [comment]
Nope didn't change any program components. I'm using g304. [Viedo](https://youtu.be/iAV6hxtTmLA)
After some test and found out that. The tray icon work normal after changing tray icon and apply it.
But after "wake up screen from auto-sleep" this bug occurred.

**Comment by irzyxa** [comment]
Probably this is your situation:
https://github.com/irzyxa/Volume2/wiki/FAQ#7-incompatibility

**Comment by Slope123** [comment]
Smooth scrolling is disable so probably not :(
Had try changing volume with keyboard but still have this issue.

**Comment by irzyxa** [comment]
What about standard Volume2 tray skin, does it work correctly?

**Comment by Slope123** [comment]
Same issue, also try setting "volume changing speed" to recommend value but still the same issue after screen auto-sleep.

**Comment by irzyxa** [comment]
Okay, what PC do you use? Any external audio devices?

**Comment by Slope123** [comment]
[PC summary.txt](https://github.com/irzyxa/Volume2/files/7646631/Report.txt)
Yes, got an external usb sound card, but I had try both "using external usb sound card" & "using onboard audio(with external usb sound card remove)".

Had try Volume2 with the same setting on my laptop and have no issue, so probably just something off with my PC.
