### ISSUE TITLE
Tray icon doesn't change

### ISSUE THREAD

**Issue by nekato** [irzyxa/Volume2#156]
If I set my tray icon to be Device icon, it won't change after I connect my Bluetooth headphones, but it does change on all other tray skins. It was working till a few days ago.
Also it changes when pressing shortcut for changing next default device. Only freezes on headphone connect.

 - Windows version: 11
 - Volume² version: v1.1.7, build 443

**Comment by irzyxa** [comment]
Could you please attach your Config.ini? Tried on my side, it works.

**Comment by irzyxa** [comment]
I think I fixed it. Version 1.1.7.444

**Comment by nekato** [comment]
All good! Awesome. Thanks.
