### ISSUE TITLE
Incredibly high CPU usage (30%)

### ISSUE THREAD

**Issue by Darkmaster006** [irzyxa/Volume2#157]
**Describe the bug**
CPU usage is constantly on the 30% range on my notebook. I've also installed it on a really good desktop PC and CPU usage is around 10%. Both are indicated as 'Very High' from Windows. Usage seems to drop to 0% when I close it and open it again. Keep in mind it's started at startup as a program. Should I change it to a task? Or start it manually? Either way, I see no reason for the High CPU usage, so it's definitely a bug.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/21136515/146436810-f8feb3a4-4326-4e98-ae4f-2bf424adfe46.png)

**Desktop (please complete the following information):**
 - Windows version: 10.
 - Volume² version: 1.1.7.444

**Additional context**
Just installed it. Change shortcuts for some stuff. Changed position of OSD. Started at startup as a program (not a task).

**Comment by irzyxa** [comment]
Could you try to use release version 1.1.6?

**Comment by Darkmaster006** [comment]
> 

Downgrade? Sure, I'll try now. I made some edits to the original post, though, so check those out. I also remember, when I used this some years ago, that the mouse dragged, not that I can reproduce it now but it may be related.

**Comment by Darkmaster006** [comment]
> Could you try to use release version 1.1.6?
Upon installing, so far this is the usage:
![imagen](https://user-images.githubusercontent.com/21136515/146438039-2d6a0e26-d5ac-4d6f-939f-fe06339218d6.png)
I'll restart, with it starting as a program at startup, and see what happens.

**Comment by Darkmaster006** [comment]
On my other PC, where I've kept the same version, and unchecked the 'start at startup', it has started at startup anyways (still enabled if I check on the section in task manager), usage is, so far:
![imagen](https://user-images.githubusercontent.com/21136515/146438976-307cb9b6-9334-4211-aa6d-bd16077f4394.png)
It seems to me that usage spikes with time? Or after some trigger? I'll let my PC stay up and see what happens.

**Comment by Darkmaster006** [comment]
On 1.1.6, on the notebook, this is the usage after restarting:
![imagen](https://user-images.githubusercontent.com/21136515/146440985-ab697df3-ea07-488c-bb32-8e9c2aadbb3a.png)
I've noticed, though, that upon opening the Settings (double clicking the icon), the mouse lags a tad, then changing between Settings, for example clicking 'Languages' and then 'Help', the mouse lags again. I could only reproduce this the first time, at least so far. I'm not sure if it has to do with the 'Mouse and mouse wheel options'.

**Comment by irzyxa** [comment]
What is your mouse? Do you use any drivers for mouse? Or other programs that use mouse?

**Comment by Darkmaster006** [comment]
> What is your mouse? Do you use any drivers for mouse? Or other programs that use mouse?

Logitech. No programs that use mouse, as I'm keeping it as minimal as I can because the computer's drive is pretty faulty. As for the usage, seems to be normal now. Not sure what cause it. Will be on the lookout. Mouse problem's still happening. It freezes when I double-click on the icon, then freezes when I click on Languages until it loads and unfreezes.

**Comment by irzyxa** [comment]
Fixed in version 1.1.7.447. 
Related item #162
