### ISSUE TITLE
Volume buttons don't work on Windows 11

### ISSUE THREAD

**Issue by EvgeniyDoctor** [irzyxa/Volume2#159]
On Windows 11, after launching this program, all volume buttons stop working: functional keys (F7 and F8 in my case) and volume buttons on the laptop case.

 - Windows version: Win 11, 21H2 22000.376, official build
 - Volume² version: 1.1.6.428
 - Laptop: HP ENVY x360

I tried to change some settings in the program, but no luck. After closing this app, all buttons works fine.
On Windows 10 on the same laptop everything worked fine a couple of days ago.

**Comment by irzyxa** [comment]
Please check Keyboard tab, are there any items?

**Comment by EvgeniyDoctor** [comment]
![Screenshot 2021-12-23 053729](https://user-images.githubusercontent.com/15073200/147163594-a0614de4-8999-42e8-8a1b-d4845a419f5c.jpg)

**Comment by irzyxa** [comment]
Perhaps on Win10 was installed some driver and for Win11 it has been changed or not installed?

**Comment by irzyxa** [comment]
Also can you check this options:
![image](https://user-images.githubusercontent.com/5119360/147275084-32425ed7-d374-4dc6-9969-62047145042b.png)

**Comment by EvgeniyDoctor** [comment]
I reinstall Volume2 a couple of times and everything works now.
