### ISSUE TITLE
Rotating mouse on taskbbar volume change problem for Win10 when a metro app is active

### ISSUE THREAD

**Issue by nhantrn** [irzyxa/Volume2#16]
I use the option to change volume when scrolling mouse wheel on the taskbbar quite a lot on Windows 7.

But now on Windows 10, when a metro app (MS Store apps, the new Setting screen, and even the Start screen) is active, the volume would change dramatically (from 0 to 80 on a 100-scale) whenever I scroll the mouse wheel just 1 notch on the taskbar. It's crazy.

I think the problem is that metro apps take control of the mousewheel for its accelerated inertia scrolling. The evidence can be seen by trying to scroll the mousewheel on a metro apps and then move the mouse on the taskbar, you can see the volume start to change by the inertia scrolling algorithm generated from the metro apps.

This also happens on IE11 for some reason too, but rarely.

**Comment by irzyxa** [comment]
This can be if you have installed Logitech SetPoint or OscarX7

**Comment by nhantrn** [comment]
Yes I have logitech SetPoint. How come it only happen with metro apps though?

**Comment by irzyxa** [comment]
Disable this option and all will be work
http://www.logitech.com/assets/48011/6/smooth-scrolling.jpg

**Comment by irzyxa** [comment]
Look please also this link 
http://support.logitech.com/en_ca/article/41666?product=a0qi00000069uj2AAA
