### ISSUE TITLE
Suddenly consuming 30% CPU when offline

### ISSUE THREAD

**Issue by dietmar4711** [irzyxa/Volume2#162]
Hi,

when offline, Volume2 suddenly starts an endless loop consuming 30% CPU and you cannot end it the normal way, you have to kill the process... just wanted to let you know that this only happens when I have no internet connection.

Version: Latest on Win10 Prof.

Regards,
Dietmar

**Comment by irzyxa** [comment]
Thank you! You save me. I spent a lot of time to find this issue.

**Comment by irzyxa** [comment]
Fixed, version 1.1.7.447
