### ISSUE TITLE
1.1.7.441 did not fully recover when Explorer crashed

### ISSUE THREAD

**Issue by baz357** [irzyxa/Volume2#165]
Today Explorer.exe had an issue and crashed a bit later. A few minutes later I noticed that Volume2's screen border volume change feature didn't work anymore. I didn't have the time to find out if and how much other Volume2 would still work, so I just ended and restarted it. Volume2's screen border volume change feature then worked again.

Not a big bug, just wanted to share in case you want to look into it. Windows 10 here, all updates installed.

Happy New Year!

**Comment by irzyxa** [comment]
Perhaps you do not enable this option https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by baz357** [comment]
Oh, you're right! Thanks, enabled now. :)
