### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by kevin-stuart** [irzyxa/Volume2#17]
On high resolution displays with resolution scaling, OSDs are too small. For example, on 3840x2196 with 200% scaling on Windows 10, OSDs should be 2x their normal size and appear the same size as if the resolution was set to 1920x1080.

**Comment by irzyxa** [comment]
You must use OSD with high resolution. I cannot scale it programmaticaly, because we will have blure effect.

**Comment by kevin-stuart** [comment]
Well off course there may be blur, but it is better than to have a blurry OSD than having one that is to small. There are almost not good OSDs and you would need N versions of an OSD, one to accommodate each level of scaling; the number of OSDs would rise drastically.

Consider this more of a feature request if you do not consider it a defect. Also consider: Scaling with even factors such as 2x does not need to result in blur, since you can map one pixel perfectly to four pixels. Only scaling to other factors such as 1.5 would require interpolation. I think it would be a good feature to have.

**Comment by irzyxa** [comment]
Ok, I understood you. I will add new percent of scale to OSD options.

**Comment by irzyxa** [comment]
Do you have the possibility to test, if I send version?

**Comment by kevin-stuart** [comment]
Yes.

**Comment by irzyxa** [comment]
Ok, can you open Config.ini file and change parameter OSDStretchPercent to 200 or 400? And send to me screen shot with results.

**Comment by kevin-stuart** [comment]
Looks good to me.
![image](https://cloud.githubusercontent.com/assets/14305901/16421568/c1aae894-3d55-11e6-835b-4b5cc71f7288.jpg)
Great work.

**Comment by irzyxa** [comment]
What percent do you used?

**Comment by kevin-stuart** [comment]
I used "OSDStretchPercent = 200". Windows was set to 200% as well, but it seems that OSDStretchPercent is independent as I also tested "OSDStretchPercent = 200" on a computer with 100% scaling and it looked the same.

**Comment by irzyxa** [comment]
Ok, thank you. I will add 200% to OSD menu.

**Comment by irzyxa** [comment]
Version 1.1.5.381
