### ISSUE TITLE
Add a black variant to the "Standard 10" Tray Icon

### ISSUE THREAD

**Issue by Ric-82** [irzyxa/Volume2#172]
I'd like to use the "Standard 10" try icon, because it's the closer to the original but, unfortunately, it comes in white while all the others icons in my system tray are black. 

Could you please add a black variant?

**Comment by irzyxa** [comment]
It is on my list to add more dark tray skins

ср, 12 янв. 2022 г., 00:30 Ric-82 ***@***.***>:

**Comment by Ric-82** [comment]
Great!

**Comment by irzyxa** [comment]
@Ric-82 Skin Standard10 Dark is available in version 1.1.8.454
