### ISSUE TITLE
Use separate control curve for different devices

### ISSUE THREAD

**Issue by d-uzlov** [irzyxa/Volume2#174]
Currently there is only one option for control curve (called "control method" in the settings).
The issue is that different devices use different mapping between volume settings in Windows and the real result loudness.

Namely, Realtek integrated audio seems to treat Windows volume as linear amplitude, so it requires logarithmic curve to be usable.
However, many other devices I have (for example, all of the Bluetooth headphones I have) seem to be doing logarithmic transform by itself, so it doesn't make sense to use logarithmic curve in Volume2, only linear is comfortable to use.

It would be much more convenient if I could set different control curve for each device.

**Comment by irzyxa** [comment]
I am going to implement it in this way. Perhaps you have better ideas how it should look, so fell free to share them.
![image](https://user-images.githubusercontent.com/5119360/149639422-51d9ea88-8a37-416a-b15d-ff3a5b874dbb.png)

**Comment by irzyxa** [comment]
Another option (I like it better)
![image](https://user-images.githubusercontent.com/5119360/149639685-6e2d0806-130a-4969-a479-448560803099.png)

**Comment by irzyxa** [comment]
Implemented in version 1.1.8.457
Final version:
![image](https://user-images.githubusercontent.com/5119360/152875823-30ddab3b-6a52-41d9-b9bb-5591f3cd2cc4.png)
