### ISSUE TITLE
Add hide tray icon option

### ISSUE THREAD

**Issue by miguelangelss4** [irzyxa/Volume2#178]
As title says, I think adding a "Hide tray icon" option would be fine. I like my tray bar as clean as possible, without hiding under Windows arrow option:
![image](https://user-images.githubusercontent.com/15887424/149752532-e0779e80-10fa-4b0a-8b9b-a6284cdba712.png)

**Comment by irzyxa** [comment]
Please use option as shown on screenshot:
![image](https://user-images.githubusercontent.com/5119360/149758381-230447d6-3617-421d-865c-036a2f17f0af.png)
