### ISSUE TITLE
Volume2.exe - Bad Image

### ISSUE THREAD

**Issue by CPU-** [irzyxa/Volume2#18]
"The application or DLL C:\Windows\system32\dxva2.dll is not a valid Windows image. Please check this against your installation diskette."

I don't know why it's looking in C: (Windows 7) because I installed the program from D: which is where the OS I normally use is installed.

I can still use the program I just have to click OK to close the box then the program opens and works fine.

**Comment by irzyxa** [comment]
Fixed, will be available in version 1.1.5.368

**Comment by CPU-** [comment]
Thanks mate!
