### ISSUE TITLE
Can't set Win + Num+ as shortcut?

### ISSUE THREAD

**Issue by Darkmaster006** [irzyxa/Volume2#180]
**Describe the bug**
I'm trying to set Win + Num+ as shortcut for 'Stand by' because that is what I use in Linux and would like the same command on Windows, I'm already used to it. I have to say I've already disabled the Magnifier, so that should be no problem (since Win + Num+ is originally the Magnifier activation shortcut). Could this be done? Thank you.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version: 10
 - Volume² version: 1.1.7.449

**Additional context**

**Comment by irzyxa** [comment]
Please past this string to LowLevelShortKeys:
Pause,"Win + 0","Win + 1","Win + 2","Win + 3","Win + 4","Win + 5","Win + 6","Win + 7","Win + 8","Win + 9","Win + Up","Win + Down","Win + Left","Win + Right",F12**,"Win + Num+"**
![image](https://user-images.githubusercontent.com/5119360/150843025-5886c479-815c-414a-bb80-959a4f766f84.png)

**Comment by Darkmaster006** [comment]
> 

Had a chance to try this just now. Setting it like this works, thank you.
