### ISSUE TITLE
Timed scheduling won't work if computer is sleeping/off at the scheduled time

### ISSUE THREAD

**Issue by tswntk** [irzyxa/Volume2#19]
I have setup two schedules:
1. set volume to 80 at 08:00
2. set volume to 35 at 22:00

They both work fine as long as the computer is running at the scheduled time else they won't woke.
I tried to set both to activate upon wake up. That seems to work - but only for one of the schedule  and I can't work out which one will click in. It could be the first one or it could be the second one which is understandable since I have two active schedules at the same condition.

I notice that you can specify a time range (Starting at and Ending at) for "every", "every minute" and "every hour" but not "every day" and " on wake up". While every hour seems too long (imagine waking up at night with a large volume and have to wait for an hour to have the vol turn down, I would set the vol manually which defeats the purpose of scheduling), every minute seems too intrusive.

It would be best if I can setup wake up schedules at different time periods e.g 
1. set volume to 80 upon wake up and time is between 08:00 to 21:59
2. set volume to 35 upon wake up and time is between 22:00 to 07:59
3. and these will also activate at 08:00 and 23:00 if the computer is running at those times. But I guess setting two more schedules just like the original two can easily "fix" this point. 

I am at Version 1.1.4.347 (10.08.2015)

**Comment by irzyxa** [comment]
Try to use version [1.1.5.369](https://onedrive.live.com/?authkey=%21AAIjM5ub8fkpr2Q&cid=4DDA864B8A0DC503&id=4DDA864B8A0DC503%21641&parId=4DDA864B8A0DC503%21640&action=locate).

**Comment by irzyxa** [comment]
Fixed version [1.1.5.377](https://irzyxa.wordpress.com/)

**Comment by tswntk** [comment]
Thanks!
Preliminary tests by setting computer clock to different times, go to sleep and then wake up works. 
Although they won't activate at the specific start time if the computer is running but that is what multiple schedules are for (my point 3)

Will report back if I encounter any bugs (unlikely :) )
Thank you very much again
