### ISSUE TITLE
Fix chocolatey package

### ISSUE THREAD

**Issue by icher** [irzyxa/Volume2#194]
Hi. Fix chocolatey package please. It links to http://volumesqr.at.ua and it's 404 for now.

**Comment by irzyxa** [comment]
Unfortunately, at the moment I do not have any site where I can upload files and get direct link to use it in chocolate. If you know one please share it.

**Comment by icher** [comment]
> Unfortunately, at the moment I do not have any site where I can upload files and get direct link to use it in chocolate. If you know one please share it.

How about github releases? It's pretty much direct links like this:

https://github.com/pbatard/rufus/releases/download/v3.17/rufus-3.17.exe

**Comment by irzyxa** [comment]
I am not sure that I can use github as storage, because on github I have only part of software is open source but program code is not open source.  So somebody can block the project because there is not any sources but exe's exists.

**Comment by irzyxa** [comment]
Fixed, it will be available soon
