### ISSUE TITLE
Brightness change popup is not showing

### ISSUE THREAD

**Issue by PavloBilyak** [irzyxa/Volume2#2]
On my notebook is installed Volume2. In options showing brightness is on but it have no effect.

**Comment by irzyxa** [comment]
This only have effect when you change brightness in Volume2(Hotkeys)
17.11.2015 8:56 пользователь Pavlo Bilyak <notifications@github.com> написал:On my notebook is installed Volume2. In options showing brightness is on but it have no effect.
