### ISSUE TITLE
Problem Windows 10 Osd Skin Dark

### ISSUE THREAD

**Issue by fre48** [irzyxa/Volume2#20]
![dark](https://cloud.githubusercontent.com/assets/18698940/14850294/4b711490-0c78-11e6-8907-e0b533ba4ff1.png)
The skin is not blue
I use the version 1.1.5.369 (16.04.2016)

**Comment by irzyxa** [comment]
What skin name Windows 10 or Windows 10 v2? And windows version?

**Comment by fre48** [comment]
Windows 10 v2 Osd Skin. Windows 7

**Comment by irzyxa** [comment]
Go to Volume2 settings, tab OSD, on selected skin press right mouse button Skin Settings - Uncheck Use Colorization. Or use Windows 10 skin.

**Comment by irzyxa** [comment]
Do you use RDP?

**Comment by fre48** [comment]
it works thanks :)
