### ISSUE TITLE
How to make the volume icon and device icon displayed together

### ISSUE THREAD

**Issue by 377981259** [irzyxa/Volume2#200]
How to make the volume icon and device icon displayed together, as shown in the following picture
![DeviceAndVolumeIcons](https://user-images.githubusercontent.com/102611355/160653686-69b8f2d4-c1d7-4fe7-9118-0bea04063126.png)

**Comment by irzyxa** [comment]
![image](https://user-images.githubusercontent.com/5119360/161045177-e5b0d0e5-0dfd-485e-9464-e22d2f346a1b.png)
![image](https://user-images.githubusercontent.com/5119360/161045245-938cae32-0bed-4e02-83dc-cfcb0741c78d.png)

**Comment by irzyxa** [comment]
![VolumeAndDeviceIconsTogether](https://user-images.githubusercontent.com/5119360/161046757-97cb6bde-d5f2-4c03-921e-ed30e08ed382.gif)

**Comment by 377981259** [comment]
> ![VolumeAndDeviceIconsTogether](https://user-images.githubusercontent.com/5119360/161046757-97cb6bde-d5f2-4c03-921e-ed30e08ed382.gif)

**Comment by 377981259** [comment]
> https://github.com/irzyxa/Volume2/wiki/FAQ#11-how-to-make-the-volume-icon-and-device-icon-displayed-together

Thank you for your answer
