### ISSUE TITLE
Icon selected on the installer did not work

### ISSUE THREAD

**Issue by BenJewell** [irzyxa/Volume2#205]
When I ran the installer I selected the option for “no change”, to use the standard windows icon for volume control. But the program still set itself to use the icon with the blue slider and number. I had to manually go in “System Tray” And select the “Standard10” skin. Minor bug, but worth noting.

 - Windows version: 10 21H2
 - Volume² version: 1.1.8

**Comment by irzyxa** [comment]
It means your icon from last install won't be changed and not using system icon, because you can be on Win 7, 8, 10, 11 and system icon is different for all systems.
