### ISSUE TITLE
Volume2 doesn't work after restarting system

### ISSUE THREAD

**Issue by jupiter104** [irzyxa/Volume2#206]
**Describe the bug**
I have Volume2 set by the default method which is using the scroll wheel on the taskbar. Unfortunately, after a system restart, it stops working. Instead, I have to move my mouse to the Windows volume icon and then it works which is already a feature of Windows 11. When I uninstall and reinstall the program, it works but again stops working after system restart or shutdown.

**Desktop (please complete the following information):**
 - Windows version: 11 (22H2 Build 22598.100)
 - Volume² version: 1.1.8.457

**Additional context**
I have StartAllBack installed which makes Windows 11 taskbar more useful for me.
I also have EarTrumpet installed which let's me control volume of individual programs.
Maybe uninstalling these programs would help but I don't want to uninstall these programs as they are quite useful to me.

**Comment by irzyxa** [comment]
Perhaps this link can resolve your issue:
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by jupiter104** [comment]
> Perhaps this link can resolve your issue: https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

I didn't have to select that one. Just ticking the run as Admin option did the trick.
By the way, excellent program. Really makes life very easy when adjusting volume.
Thank you for your work.
