### ISSUE TITLE
Windows Default Recording Device selection

### ISSUE THREAD

**Issue by wraeuk** [irzyxa/Volume2#207]
I use Volume2 primarily as a microphone mute hotkey (which it's *excellent* at.)

It would be handy to be able to set the Audio device in Settings>Main to "Windows Default Recording Device" so that the setting is resistant to hotplugs/bluetooth devices changing and all that jazz.

Right now if a recording device is selected and it gets unplugged, Volume2 defaults to "Windows Default" which turns my hotkey into an output mute, until I go back in and change it to a recording device.

**Comment by irzyxa** [comment]
![image](https://user-images.githubusercontent.com/5119360/186959059-8094e21a-5646-4646-acc4-2261ef6339d6.png)
