### ISSUE TITLE
Volume change with mouse scroll over taskbar stops working once additional screen is plugged in

### ISSUE THREAD

**Issue by aleqcz** [irzyxa/Volume2#209]
Hi all,
    I am experiencing an issue - as soon as my laptop goes to sleep and resumes or when additional screen is plugged in (like a laptop cover is opened or additional screen is turned on), the volume change with mouse scroll over taskbar stops working. I need to restart volume2 again in order to restore this functionality. Is it a known bug, could it be fixed, please?

Thanks,
    A.

Volume2 version: 1.1.7.449
Windows version: Windows 11
WOW64: True
Version: Installed

**Comment by irzyxa** [comment]
Hi, let's try to update your version to the latest one:
https://irzyxa.blogspot.com/p/downloads.html
Another solution can be found here:
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile
