### ISSUE TITLE
Make visual effects optional

### ISSUE THREAD

**Issue by dogancelik** [irzyxa/Volume2#21]
**Problem 1**
Single-clicking Volume2 opens Volume bar with a half second delay.
Example: in qBittorrent, when you click tray icon with mouse, it opens the window immediately (no delay).

**Problem 2**
Volume bar hides very slowly, I want to disable that fade effect (transparency) completely.

**Comment by irzyxa** [comment]
Problem 1
It's because we have option to double click, and other programs doesn't have.
Problem 2
This can be added as option

**Comment by irzyxa** [comment]
Version 1.1.5.381
Change paramter ImmediateHideVolumeControl to 1 in Config.ini
