### ISSUE TITLE
Windows sound settings in the context menu

### ISSUE THREAD

**Issue by onestepbeyond** [irzyxa/Volume2#210]
Hi, 
Possible to add in the context menu an item opens Windows sound settings page? like [ms-settings:sound] command.  
Thanks!

**Comment by irzyxa** [comment]
I added SoundSettingsApplication option to UserVariables:
![image](https://user-images.githubusercontent.com/5119360/172101961-67b6feac-a074-4752-bff0-3acf436e5b0b.png)

**Comment by irzyxa** [comment]
It will be available in version 1.1.8.459
