### ISSUE TITLE
Question before buy.

### ISSUE THREAD

**Issue by p6002** [irzyxa/Volume2#213]
Can I control volume in two different outputs by shortcuts on keyboard at this same time? 
For example HDMI output with sound on external display, and laptop speakers with other apps. 
So I can setup page up/page down for HDMI volume, and home/end for laptop speakers?

**Comment by irzyxa** [comment]
Yes, you can. Also you can download it for free to check this: [https://irzyxa.blogspot.com/p/downloads.html](url)
![image](https://user-images.githubusercontent.com/5119360/168422462-7c554751-1e16-46c1-9e1e-61e05ebb8dfa.png)

**Comment by p6002** [comment]
How you set a device to controll? I can set only Action and Key option:
https://i.ibb.co/KGVXvwS/Zrzut-ekranu-2022-05-15-161430.png

**Comment by irzyxa** [comment]
Please see: Volume Up (alternative device)
