### ISSUE TITLE
Volume2 and DNS

### ISSUE THREAD

**Issue by andika207** [irzyxa/Volume2#214]
**Ask your question**

why is this software utility associated to dev.ucoz.net domain ?

<a href='https://postimg.cc/phNVnRZm' target='_blank'><img src='https://i.postimg.cc/76h5dLJn/Snap-Crab-No-Name-2022-5-17-5-26-43-No-00.png' border='0' alt='Snap-Crab-No-Name-2022-5-17-5-26-43-No-00'/></a>

**Comment by irzyxa** [comment]
What version do you use?

**Comment by andika207** [comment]
I have unistalled and reinstalled the same program version and now problem is gone.
I still don't understand why a russian program was making connections to this russian server... maybe it was an infected version.

**Comment by irzyxa** [comment]
Volume2 is not russian program, I am from Ukraine so it is Ukrainian software.

**Comment by andika207** [comment]
@irzyxa I'm sorry for the confusion because there's no Ukraine flag or message on this profile page. 
I wonder if @Feodor2 is also from Ukraine because he has this flag on the MSNF forum
