### ISSUE TITLE
Changing volume sound in Volume² v1.1.8, build 458 (25.05.2022)

### ISSUE THREAD

**Issue by nvthinh75** [irzyxa/Volume2#216]
I don't think that (#97) is an issue which has been fixed recently. I like to listen to ticking sounds when the volume is changing.

Please revive it back or make an option for it to play "a sequence of sounds" or "a single sound".

**Comment by irzyxa** [comment]
You can change DelayBeforePlaySound to 10
https://user-images.githubusercontent.com/5119360/170267499-1584736b-ae30-41cf-9b32-732c5f79d6d0.png

**Comment by nvthinh75** [comment]
Thank you!
