### ISSUE TITLE
Using the Github space "Releases" as Downloadspace

### ISSUE THREAD

**Issue by blackcrack** [irzyxa/Volume2#219]
Hi  Alex,

could you maybe use the "Releases" for upload the packages.. 
i don't use OneDrive and have my own Cloud(Nextcloud) and i don't like MS-OneDrive.. why ? 
MS have mostly all in the Hands.. and therewith also div. Facilitys of US and because also the Politics of MS..
they have also buy Github, i know.. but the Github account is an other as MS-Account.. and is free connectionable also for non logged in peoples,  so and the most Developers and Users be in Github.. so, 
please use the "Volume²/Releases" to update your actual releases for download..
what maybe a bit more reasonable/rational is

best
Blacky

**Comment by irzyxa** [comment]
Done.

**Comment by blackcrack** [comment]
@irzyxa thank you, now can i ever monitoring your' newest Release ! :))))))))
and the others also :)
best and big fad thank you :)
