### ISSUE TITLE
Minimum (and maximum) for volume

### ISSUE THREAD

**Issue by mohammad-rastkar** [irzyxa/Volume2#220]
Hi, I need to prevent volume level decreasing from a certain amount (like 20%).
I think it's a good feature to be added in the settings (min and max for volume-level), even if it only works when using volume keys on the keyboard.

**Comment by irzyxa** [comment]
You can try to use control method - Table on Main tab.
So here you can set max and min volume values.

**Comment by irzyxa** [comment]
![image](https://user-images.githubusercontent.com/5119360/186938100-691c0cff-5740-45d3-9417-75a2c8c6a2a1.png)
