### ISSUE TITLE
Active Application is not working.

### ISSUE THREAD

**Issue by Dejaks47** [irzyxa/Volume2#222]
Using the active application setting for changing volume is seemingly detecting my headphones as the active application, and as such is just changing the volume of my headphones, which changes the entire systems sounds.

Using latest version, running as admin, and on windows 10.
If it matters, headphones are Sony WH-1000xm4

**Comment by irzyxa** [comment]
What are your settings on main screen?

**Comment by Dejaks47** [comment]
![Screenshot 2022-07-29 200243](https://user-images.githubusercontent.com/110124343/181868770-90931a1f-d820-48d6-af8e-42f58dda6f00.png)

**Comment by irzyxa** [comment]
Please try to use the latest version: https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.458

**Comment by Dejaks47** [comment]
Thank you very much, working perfectly! Love this application
