### ISSUE TITLE
Only "linear" display is correct, "logarithmic" and "table" display are both wrong.

### ISSUE THREAD

**Issue by 6Tom** [irzyxa/Volume2#227]
**Please see the gif below**

**Screenshots**
Linear: only this is correct. It is the same as the system.
![动画3](https://user-images.githubusercontent.com/88385016/187431983-b0316d9b-1963-404d-ac91-5d8b0031b505.gif)

Logarithmic: wrong. The system shows the correct display.
![动画4](https://user-images.githubusercontent.com/88385016/187432065-9b8d8c6a-03e2-4d62-ab24-20dd04eece2c.gif)

Table: wrong. The system shows the correct display.
![动画5](https://user-images.githubusercontent.com/88385016/187432149-94c02f47-9b6b-402b-bf6d-78333ad2216e.gif)

**Desktop (please complete the following information):**
 - Windows version: 10  21H2  (up to date)
 - Volume² version: 1.1.7.449

**Additional context**
Dear irzyxa, thanks for your hard working. Volume2 is really a very good software. Looking forward to your reply.

**Comment by irzyxa** [comment]
It is correct behavior, because Windows indicator cannot display logarithmic or table values as it shows Volume2.

**Comment by 6Tom** [comment]
Oh thanks, the reply is so fast. I have a serious delay in receiving, forgive me. 

But what I mean is that windows shows the correct volume, but volume2 does not.

For example, when I use "logarithmic", I press the hotkey I set and rotate my mouse wheel, to adjust the volume to 50 showed on "osd". But the real volume of the system is very small. The volume mixer of the system shows that the current volume is 7. Obviously, the latter is correct.

I mean, when it is set to "logarithmic", volume2 successfully sets the system volume according to the "logarithmic", but the display is incorrect.

I have done tests on my computer and VMware virtual machine, and they are all like this. So I think there is no problem with my system. That's why I said volume2 has a wrong display.

**Comment by irzyxa** [comment]
To control volume as logarithmic I use specific formula to calculate volume for each step and that's why you see so small value in standard indicator.

**Comment by 6Tom** [comment]
Thanks, I understand now.

Um, please don't mind, then I have a new question: is there a way to make the "osd" display the same way as the system? Maybe I prefer the small value display mode.

**Comment by endolith** [comment]
Can it not use the underlying decibel values?  
![image](https://user-images.githubusercontent.com/58611/187459427-97e239f5-ce67-4c82-941e-6e40db06404c.png)

**Comment by 6Tom** [comment]
Um, sorry I don't understand, what does that mean?

**Comment by endolith** [comment]
I mean that the underlying hardware uses decibel settings (logarithmic), not percent (linear).  Windows just converts it to a "percent of full range" display, with some non-linear mapping, in an attempt at simplifying things, but the percent levels aren't really meaningful or comparable between cards or operating systems.  It would be best to show the decibel levels directly if that's possible.

**Comment by irzyxa** [comment]
![image](https://user-images.githubusercontent.com/5119360/187549282-32b0145b-e0e5-4d40-b4f9-50c671b7ded7.png)
Unfortunately i can use only value from 0 to 1 to control system volume.

**Comment by 6Tom** [comment]
Oh, these are beyond my understanding. Anyway, thank you very much for helping.
