### ISSUE TITLE
Exception: Invalid characters in path

### ISSUE THREAD

**Issue by zieren** [irzyxa/Volume2#228]
**Describe the bug**
A few seconds after starting the program, an exception is thrown:

```Exception EArgumentException in module Volume2.exe at 0004468E. Invalid characters in path.```

I can still use the mouse wheel on the task bar to control the volume, and the OSD is shown normally. But after dismissing the error the program terminates.

I updated to the latest version mentioned below, but to no avail. The above address is from that version.

**Screenshots**
![volume2_exception](https://user-images.githubusercontent.com/9637943/188263914-0914bd46-aa02-4830-9df2-2fe4d85de03e.png)

**Desktop (please complete the following information):**
 - Windows version: 10, 21H2 (Build 19044.1889)
 - Volume² version: 1.1.7.449

**Additional context**
I was using an older version (about a year old) when this happened and hadn't changed anything, AFAIR. But I do have Windows automatic updates enabled. Maybe worth noting that my username (and thus profile folder) contains a non-ASCII character (a German umlaut). This was maybe a bad idea but has actually never caused any problems, and it might be a red herring (it definitely didn't change).

**Comment by irzyxa** [comment]
Please attach your Error.log file.
https://github.com/irzyxa/Volume2/wiki/FAQ#4-where-is-configini-located

**Comment by zieren** [comment]
Sorry, I forgot that. No smoking gun though, ISTM, unless something is missing.

```
03.09.2022 10:55:33	DEBUG	LoadSettings succeeded
03.09.2022 10:55:33	DEBUG	LoadLangList succeeded
03.09.2022 10:55:33	DEBUG	LoadDevicesList succeeded
03.09.2022 10:55:33	DEBUG	LoadVistaDevicesList succeeded
03.09.2022 10:55:33	DEBUG	OpenSoundDevices succeeded
03.09.2022 10:55:33	DEBUG	Set Mute Value succeeded
03.09.2022 10:55:33	DEBUG	LoadSkinsList succeeded
03.09.2022 10:55:33	DEBUG	LoadOSDSkinsList succeeded
03.09.2022 10:55:33	DEBUG	LoadSoundsList succeeded
03.09.2022 10:55:33	DEBUG	LoadSkinsToTray succeeded
03.09.2022 10:55:33	DEBUG	LoadHotKeysInfo succeeded
03.09.2022 10:55:33	DEBUG	RegHotKeys succeeded
03.09.2022 10:55:33	DEBUG	SetKeyBoardHook succeeded
03.09.2022 10:55:33	DEBUG	WTSRegisterSessionNotification Result = True
03.09.2022 10:55:33	DEBUG	RegisterProtocol Result = True
03.09.2022 10:55:53	DEBUG	LoadSettings succeeded
03.09.2022 10:55:53	DEBUG	LoadLangList succeeded
03.09.2022 10:55:53	DEBUG	LoadDevicesList succeeded
03.09.2022 10:55:53	DEBUG	LoadVistaDevicesList succeeded
03.09.2022 10:55:53	DEBUG	OpenSoundDevices succeeded
03.09.2022 10:55:53	DEBUG	Set Mute Value succeeded
03.09.2022 10:55:53	DEBUG	LoadSkinsList succeeded
03.09.2022 10:55:53	DEBUG	LoadOSDSkinsList succeeded
03.09.2022 10:55:53	DEBUG	LoadSoundsList succeeded
03.09.2022 10:55:53	DEBUG	LoadSkinsToTray succeeded
03.09.2022 10:55:53	DEBUG	LoadHotKeysInfo succeeded
03.09.2022 10:55:53	DEBUG	RegHotKeys succeeded
03.09.2022 10:55:53	DEBUG	SetKeyBoardHook succeeded
03.09.2022 10:55:53	DEBUG	WTSRegisterSessionNotification Result = True
03.09.2022 10:55:53	DEBUG	RegisterProtocol Result = True
```

**Comment by irzyxa** [comment]
I do not see any issues. Please try to use the latest version https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.458

**Comment by zieren** [comment]
The pre-release version works, thanks!
