### ISSUE TITLE
2nd device icon won't appear

### ISSUE THREAD

**Issue by SullyPanda76cl** [irzyxa/Volume2#232]
**Describe the bug**
Have 2 devices on PC. 
Only 1 device icon appears

**Screenshots**
![Screenshoot](https://i.imgur.com/NIfRAFg.png)

**Desktop (please complete the following information):**
 - Windows version: 10.0.22622.601
 - Volume² version: 1.1.7.449

**Comment by irzyxa** [comment]
![image](https://user-images.githubusercontent.com/5119360/191943959-49e85379-f44a-4a8d-add5-f135753639bc.png)
