### ISSUE TITLE
Volume2 interfering with HideVolumeOSD (error fix?)

### ISSUE THREAD

**Issue by Rechain** [irzyxa/Volume2#233]
I am using both, but if HideVolumeOSD and Volume2 is starting at the same time with Windows it gives me the "Severe error: OSD window not found" from HideVolumeOSD. I need to open HideVolumeOSD first, then Volume2 and it works without issues. HideVolumeOSD can't find the OSD window cause Volume2 already running in the background also hiding some of it. Any chance for a fix where both programs works better together, so I don't have to do this every time myself in the correct order at Windows login? Many thanks no matter what happens :) I will provide this post on the HideVolumeOSD github as well.

**Comment by irzyxa** [comment]
Volume2 does not hide any OSD windows. It shows its own OSD. And Volume2
hooks VolumeUp/Down keys to change volume and send system its identity and
in this case system doesn't show OSD window.

сб, 24 сент. 2022 г., 11:22 Rechain ***@***.***>:

**Comment by Rechain** [comment]
The error in HideVolumeOSD happens when Volume2 is loaded into Windows first. When I shut it down, I can activate HideVolumeOSD without the error. So there is an interfering no matter what. Whatever is going on, I have no idea. The only thing I know is that I replicate the issue every time I turn on the PC and have to open those 2 programs in the correct order 🤔

**Comment by Rechain** [comment]
The error in HideVolumeOSD happens when Volume2 is loaded into Windows first. When I shut it down, I can activate HideVolumeOSD without the error. So there is an interfering no matter what. Whatever is going on, I have no idea. The only thing I know is that I replicate the issue every time I turn on the PC and have to open those 2 programs in the correct order 🤔

**Comment by Rechain** [comment]
After some more testing, after they are opened in the right order I can close HideVolumeOSD and open without the error. HOWEVER, at startup when Volume2 is loaded and I try to open HideVolumeOSD, it shows the Volume2 hud while giving the error. After some time, it show up without hiding anything but then gives an Unhandled Exception error from Microsoft .NET Framework but it now works (still giving the error, when enable or disabling HideVolumeOSD) while it show the Volume2 OSD briefly (that I have activated). Until I close down Volume2, I can open HideVolume2 without issues and then Volume2 so they work together. This is very odd and strange behaviour?

**Comment by irzyxa** [comment]
What versions of software do you use?

**Comment by Rechain** [comment]
Volume2 is version 1.1.8.458 (latest when I press to check) and HideVolumeOSD is 1.2.0.0 (should be latest, that actually should fix the severe error, but not with Volume2 in mind). Also got the bug that Volume2 won't stop starting with Windows even though it's disabled, and have checked the task manager for startup already and there is nothing (have not manual added to startup).

**Comment by Rechain** [comment]
Where the fix should be found, and in which program (Volume2 or HideVolumeOSD) is a good question 🤔

**Comment by irzyxa** [comment]
This link shows that HideVolumeOSD shows message you see. So it should be removed.
https://github.com/UnlimitedStack/HideVolumeOSD/blob/master/HideVolumeOSD/HideVolumeOSDLib.cs#L111

**Comment by irzyxa** [comment]
Or you can remove the following combinations from Volume2 settings:
![image](https://user-images.githubusercontent.com/5119360/192099834-465990b0-cb21-4f3b-9307-17eae8c2072f.png)

**Comment by Rechain** [comment]
That seems a bit weird, but okay 😲 I removed those keyboard combinations, since I don't know about the other thing.
