### ISSUE TITLE
Tray icon doesn't update after device reinitialization

### ISSUE THREAD

**Issue by dezdem** [irzyxa/Volume2#234]
I have an external audio interface with USB type-B (square) connector, a light touch might cause it to lose the connection for a moment.
Whenever this happens Volume2 tray icon stops updating its status, i.e. the volume level indicator freezes at certain value and doesn't update, or a red cross signaling that interface is not available appears, though the sound works and I can adjust the volume using Volume2 with a mouse scroll.
I have to restart the app in order to fix this. This started happening after some V2 update, a year or so ago.

**Comment by irzyxa** [comment]
What about your program version?

**Comment by dezdem** [comment]
> What about your program version?

It's the latest release
1.1.7.449

**Comment by irzyxa** [comment]
Please use the latest one
https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.458

**Comment by dezdem** [comment]
> Please use the latest one https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.458

Thanks, it helped with frozen volume level, but the issue with a cross in a red circle is still present.

**Comment by irzyxa** [comment]
Could you add some screenshots or short video?

**Comment by dezdem** [comment]
> Could you add some screenshots or short video?

https://i.imgur.com/DX40Vd8.jpeg

Sometimes it shows this even if the device is available.
