### ISSUE TITLE
Mouse cursor movement stuttering, when holding down any keyboard key

### ISSUE THREAD

**Issue by 333hronos** [irzyxa/Volume2#235]
**Describe the bug**
Mouse cursor movement stuttering, when holding down any keyboard key.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version: Win 10 21H2 19044.2130 (Windows Feature Experience Pack 120.2212.4180.0)
 - Volume² version: 1.1.4.347

**Additional context**
If not appear instantly after program start, maybe, it will appear only after using sleep mode multiple times.

**Comment by 333hronos** [comment]
Thanks, old version somehow doesn't show me that it has an update. Now I will try the new version for several weeks and text here in a result.

**Comment by irzyxa** [comment]
Please read advice from here, probably you will find solution. Perhaps you have installed incompatible apps.
[FAQ](https://github.com/irzyxa/Volume2/wiki/FAQ)

**Comment by Spuner** [comment]
> Perhaps you have installed incompatible apps.

I don't quite know what you mean?

**Comment by Spuner** [comment]
> https://github.com/irzyxa/Volume2/wiki/FAQ#7-incompatibility

I don't have anything that's on the list.

**Comment by Spuner** [comment]
As I understand it, this problem will not be solved, right?

**Comment by irzyxa** [comment]
It's hard to fix it if you can't reproduce it. Could you send list of installed applications from your PC? Probably there is one more application that is not compatible with Volume2.

**Comment by Spuner** [comment]
> It's hard to fix it if you can't reproduce it. Could you send list of installed applications from your PC? Probably there is one more application that is not compatible with Volume2.

Standard key "Mute" on the keyboard (Steelseries Apex 3) - works properly, without cursor freezes. But if you assign to this key to mute in Volume2 - lags start. The problem is not in the system, and not in third-party programs.

**Comment by irzyxa** [comment]
@Spuner What is your Windows version? And could you record video have it looks like? Because I cannot reproduce it, I tried different combinations and it works.

**Comment by Spuner** [comment]
@irzyxa here's the [video](url=https://ru.files.fm/f/tqqxvug85). I hope it helps...

**Comment by irzyxa** [comment]
What device do you use? It is not integrated audio card, correct? Could you try to use another audio device?

**Comment by Spuner** [comment]
This is a integrated sound card - Realtek USB Audio (Codec - Realtek ALC4080).

**Comment by irzyxa** [comment]
Please try to disable OSD.
![image](https://user-images.githubusercontent.com/5119360/208641355-d645aa98-45b1-4cb3-84ca-892eac4e043c.png)

**Comment by Spuner** [comment]
One of the first things I did was to turn off the OSD, but unfortunately it didn't help. I must have tried everything...

I noticed that there are no such problems in the Key Manager program.

**Comment by Spuner** [comment]
By the way, I noticed that in AutoHotKey is also all right with the switching on and off sound.

**Comment by irzyxa** [comment]
Possible duplicate:
https://github.com/irzyxa/Volume2/issues/185

**Comment by Spuner** [comment]
MoneyAllDay has the same problem (apparently), but solving the problem as not installing for the sound card driver is not the solution. As I said above, in programs such as Key Manager or script AutoHotKey - this problem does not exist.

**Comment by irzyxa** [comment]
Please try to disable Mouse actions.
![image](https://user-images.githubusercontent.com/5119360/209709301-b6b89e64-78b2-44e7-bce2-bfc38da0cd2d.png)

**Comment by Spuner** [comment]
Apparently it helped. But what are these Mouse actions?

**Comment by irzyxa** [comment]
It disables mouse hook and you cannot use mouse scroll to control volume

**Comment by Spuner** [comment]
I don't use the mouse wheel to adjust the volume. So, in my case, this is the solution to the problem. (hopefully the final solution)
