### ISSUE TITLE
Master volumn control for all devices

### ISSUE THREAD

**Issue by zeroarst** [irzyxa/Volume2#237]
I would like to know if there is a way to have a master volumn across all devices?
Currently I have a headphone and speaker devices, both sometimes have different volumn.
When I switch from one to the other, the sound volumn could blast.
What I want is, if I can have just one volumn control that applies to all devices, that would be great!
Or at least, can adjust all at the same time. So I can set them to the same level, and while I am adjusting, it applies to all.

**Comment by irzyxa** [comment]
I want to recommend you to configure task as shown in the screenshot:
![image](https://user-images.githubusercontent.com/5119360/209701316-99471672-1bac-4027-b870-7809b0d82757.png)
