### ISSUE TITLE
Installation Error: Couldn't read TOC. Aborting.

### ISSUE THREAD

**Issue by ttqftech** [irzyxa/Volume2#238]
When trying to launch install program on Windows 11 22H2, this error occured.
![image](https://user-images.githubusercontent.com/31009285/206836410-025ec868-cdc5-4f08-8a1c-8e52e5216cb4.png)
This problem seems not occured in older version of Windows 11. Thus I can only use my left program installed previously and can't update or reinstall it.
If it's hard to fix this problem, could you provide a portable version of volume²?

**Comment by irzyxa** [comment]
Here you can download the latest version:
https://github.com/irzyxa/Volume2/releases
Talking about issue: this message can be shown if you try to run installer from archive so please unpack installer in any place on your PC and then start installation.

**Comment by ttqftech** [comment]
Discovered more detail:
When the setup exe is in system drive, it can run normally.
When the setup exe is NOT in system drive, Couldn't read TOC. Aborting.

**Comment by 74ls00** [comment]
The installer path must not contain "Volume²" characters.
Developers need to rename the "Volume²" package to "Volume2"
