### ISSUE TITLE
Multiple devices control volume

### ISSUE THREAD

**Issue by vladichimescu** [irzyxa/Volume2#239]
Can we get support for multiple alternative audio devices instead of only one that is currently implemented?

Benefits: having multiple alternative audio devices would give users ability to volume control multiple outputs with Voicemeeter using a single audio source.

Current situation: in **Main**, you can define the **Audio device** as **Windows Default** and enable **Lock Devices Volume** to an **Alternative audio device** which will give you native audio control over 2 devices.

**Comment by irzyxa** [comment]
@vladichimescu please review this task #264 probably it resolves your request
