### ISSUE TITLE
Tray Icon Doesn't Change As Volume Changes After Computer Awakes From Sleep

### ISSUE THREAD

**Issue by Dypsis** [irzyxa/Volume2#240]
After waking the computer from sleep, when I mouse scroll on the Taskbar to change the volume, the tray icon doesn't change and is frozen at the last volume level before sleep. If I exit out of Volume2 and restart it, it works again.

**Comment by irzyxa** [comment]
Here is solution:
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by Dypsis** [comment]
Thanks, Alexandr.
I'll try that. 🙂

**Comment by Dypsis** [comment]
It's not working. 😞

**Comment by irzyxa** [comment]
What version of application do you use?

**Comment by Dypsis** [comment]
Volume2 v1.1.8.458 on Windows 11.
