### ISSUE TITLE
Hardware Volume Keys not working without Volume2

### ISSUE THREAD

**Issue by nitincodery** [irzyxa/Volume2#247]
When Volume2 is closed, hardware keys in laptop isn't working anymore.

 - Windows version: 10 (22H2) (Build: 19045.2486)
 - Volume² version: 1.1.8.458 (25.05.2022)

**Comment by irzyxa** [comment]
Volume2 cannot work with them at all
https://github.com/irzyxa/Volume2/wiki/FAQ#6-fn-keys

Probably you should install specific software for your laptop

**Comment by nitincodery** [comment]
I have dedicated volume up and down keys without fn combination keys or function keys, dedicated volume up and down keys were working before volume2  but now if I close the program, my volume keys aren't working, where I can reset them to default?

**Comment by githubbapoopa** [comment]
This was also very annoying for me on my ThinkPad. I found out that Config.ini has an entry "DisableVolume2Keyboard=1". By uncommenting this (or setting it to =0) hardware keys work again.

So please disable this by default.

Btw. Fantastic program!

**Comment by irzyxa** [comment]
> 

Volume2 does not remove any default settings it just hooks keys when it is running

**Comment by irzyxa** [comment]
DisableVolume2Keyboard can be controlled using context menu
![image](https://github.com/irzyxa/Volume2/assets/5119360/965844e9-f2a1-4391-8c95-a561fda11afe)
