### ISSUE TITLE
Dynamic Tray Icon depending upon system theme

### ISSUE THREAD

**Issue by iamMG** [irzyxa/Volume2#248]
I use the "Volume2 Default Black" tray icon during the day when my system is not on Dark mode. I want the tray icon to automatically switch to "Volume2 Default White" during night when I turn on Dark mode (actually I automate it using the app [AutoDarkMode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode)). Currently, either I manually go to settings and change the tray icon, or automate the process using AutoHotKey and directly edit the Config.ini file. It is quite cumbersome.

Please add a setting to automate the icon change. I have read several changelogs of Volume2 and seen 'alternate tray icon' being mentioned multiple times, but it is still not clear to me how to enable whatever that is.

**Comment by irzyxa** [comment]
I have started implementing this feature. It will be added to Interface Settings screen and you can set Tray Skin/Alt Tray Skin (OSD in the future) for dark mode
![image](https://user-images.githubusercontent.com/5119360/218335557-5567a192-e8b6-4eaf-931d-a59e44f70fe3.png)

**Comment by iamMG** [comment]
Thanks. I will be waiting for this update!
