### ISSUE TITLE
When hovering mouse at Volume2 icon in tray, name of the program appears instead of the expected volume level number.

### ISSUE THREAD

**Issue by isshininu** [irzyxa/Volume2#25]
When hovering mouse at Volume2 icon in tray, name of the program appears instead of the expected volume level number.

Когда наводишь курсор мыши на иконку программы на панели задач, высвечивается название программы вместо ожидаемого значения текущей громкости.

![1111](https://cloud.githubusercontent.com/assets/6324523/17016672/3b8ee7da-4f41-11e6-9cba-d427890f6619.png)

**Comment by irzyxa** [comment]
Go to program options, tab System Tray, and check option Show tooltip (%D: %V%), Style = Simple.
Откройте настройки программы, вкладка Системный трей, включите опцию Включить подсказку(%D: %V%), и выберите Стиль всплывающей подсказки: Обычный
