### ISSUE TITLE
BUG: Serious problem with merging Korean

### ISSUE THREAD

**Issue by VenusGirl** [irzyxa/Volume2#252]
**Describe the bug**

![Volume2-문제1](https://user-images.githubusercontent.com/53147200/218307221-63bae99b-a61f-4326-bb46-89068cb3d423.png)
![Volume2-문제2](https://user-images.githubusercontent.com/53147200/218307467-8b80d8cc-f85e-4bd1-bd12-831ea366ac0c.png)

**Desktop (please complete the following information):**
 - Windows version: [11 (22H2)]
 - Volume² version: [Volume² 1.1.8.461]

**Additional context**
There is a serious problem with Korean merging.
The current string is all empty.
So it's not being displayed in Korean.

**Comment by VenusGirl** [comment]
Files with serious issues:
Korean.lng, Polish.lng, Translate.xlsm

**Comment by irzyxa** [comment]
My fault, working on fix

**Comment by irzyxa** [comment]
Fixed

**Comment by VenusGirl** [comment]
Good!
It works fine.
Thank you.
