### ISSUE TITLE
Feature request: Add Korean to Volume2 installation script

### ISSUE THREAD

**Issue by VenusGirl** [irzyxa/Volume2#253]
**Describe the solution you'd like**
![Volume - Installer](https://user-images.githubusercontent.com/53147200/218309067-5958d0ee-50c0-45d0-874b-bc2604132096.png)

I want to add Korean to the Volume2 installation script.
If you have a string to translate, please send it to me.

**Comment by irzyxa** [comment]
Yes, it is possible. Here is an English translation for installer:
[lang_eng.zip](https://github.com/irzyxa/Volume2/files/10715975/lang_eng.zip)

**Comment by VenusGirl** [comment]
It was translated into Korean.
[lang_kor.zip](https://github.com/irzyxa/Volume2/files/10716206/lang_kor.zip)

**Comment by irzyxa** [comment]
Some more files should be translated: 
[Theme.zip](https://github.com/irzyxa/Volume2/files/10716510/Theme.zip)
For all files please translate items where **translation language="1042"** will be found.

**Comment by irzyxa** [comment]
@VenusGirl any news here?

**Comment by VenusGirl** [comment]
[Theme-Korean.zip](https://github.com/irzyxa/Volume2/files/10836589/Theme-Korean.zip)

Korean translation is included.

**Comment by irzyxa** [comment]
Done. [Download](https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.463)

**Comment by VenusGirl** [comment]
The descriptions of MultiUser mode and SingleUser mode are reversed.

![Volume2 이미지 001](https://github.com/irzyxa/Volume2/assets/53147200/99b1ddb2-29cd-46b9-b5dc-dda74f53b3fd)

UserMode.adt
![Volume2 이미지 002](https://github.com/irzyxa/Volume2/assets/53147200/d21d6671-4adf-43c6-b7fb-cf03aaa3fc9f)

Attach the corrected theme.
[Theme.zip](https://github.com/irzyxa/Volume2/files/11994464/Theme.zip)

**Comment by irzyxa** [comment]
Do you mean Korean language? Because in the screenshot it looks okay.

**Comment by VenusGirl** [comment]
The descriptions of all languages have been changed.
