### ISSUE TITLE
Add option for application/system volume up/down for keyboard shortcuts

### ISSUE THREAD

**Issue by kirpi-1** [irzyxa/Volume2#254]
I would like to be able to set a parameter for volume up/down (or have a separate action) for the keyboard combinations.

Something like I'd be able to use Alt+wheel up/down for system volume and shift+ wheel up/down for application in focus volume.

**Comment by kirpi-1** [comment]
Hm, this didn't work as it (once I set this I could only change the active application), but then putting Alternate audio device to "No" created the behavior I wanted (alt+up/down for master volume, shift+up/down for application focus volume)

![Screenshot 2023-02-21 235752](https://user-images.githubusercontent.com/25854160/220526106-adb89bfd-9ca0-40ae-b338-2f11c2d71692.png)
![Screenshot 2023-02-21 235815](https://user-images.githubusercontent.com/25854160/220526108-16641b46-b6ff-4476-874f-ee2189e9e76a.png)

**Comment by irzyxa** [comment]
I think it just conflicts with option al device so please change it as shown on screenshot and return back Alt device. 
![image](https://user-images.githubusercontent.com/5119360/220549142-5079e71b-bf6f-4cfe-92ad-035728a814fc.png)
