### ISSUE TITLE
Bug with mute

### ISSUE THREAD

**Issue by Spuner** [irzyxa/Volume2#255]
Pressing the key combination to mute - the sound is off and then back on, but all the subsequent times - works fine. This happens if you run Volume2 for the first time.

**P.S.** If you need, I can show you on video.

**Comment by irzyxa** [comment]
Yes, please attach a video.

**Comment by Spuner** [comment]
Unfortunately, I can't post it here - the file size is more than 10MB. I uploaded it to the cloud - https://fex.net/s/ctokpat

Sorry for the quality, I had to record with my phone camera... (with screen recording - there is no way to capture this bug) The music was included on purpose, so that the manifestation of the bug was evident.

**Comment by irzyxa** [comment]
I suppose you use alternate device, correct?

**Comment by Spuner** [comment]
The settings are like this.

![2023-02-24-15-59-33](https://user-images.githubusercontent.com/30773815/221174082-008db2de-941a-491c-bcb7-894ca1e98b14.png)

**Comment by Spuner** [comment]
![2023-02-24-16-03-42](https://user-images.githubusercontent.com/30773815/221174679-3908cab4-597d-4e42-85e5-b39a684b2cf0.png)

**Comment by Spuner** [comment]
This happens when Volume2 is running. But if you don't close it, then all subsequent times - everything works fine. It turns out that every time you start Windows - this bug occurs.

**Comment by irzyxa** [comment]
Okay, please send your Config.ini 
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

**Comment by Spuner** [comment]
[Config.zip](https://github.com/irzyxa/Volume2/files/10823943/Config.zip)

**Comment by Spuner** [comment]
@irzyxa, did you find out anything?

**Comment by irzyxa** [comment]
Sorry, cannot reproduce on my side. Let's try to use another combination. And probably you have something else that can turn on the volume.

**Comment by Spuner** [comment]
But I told You that this problem is only when Volume2 is first started. You can also see it on the video. If there was a conflict with other software, it would always happen, not only when Volume2 is first run.

**Comment by irzyxa** [comment]
What about using for example Ctrl+F2?

**Comment by Spuner** [comment]
I tried different combinations. It's the same with all of them.

**Comment by Spuner** [comment]
The situation is this: in version 1.1.6 (Build 428) - this bug does not. Everything is working fine. Starting with 1.1.7 (Build 449) - the bug is present. Older versions of builds 1.1.7 - I unfortunately do not have, to check.

**Comment by irzyxa** [comment]
Try to disable this option
![image](https://user-images.githubusercontent.com/5119360/221401449-bed7a2bc-5d23-4c5d-8af1-cec173a9a976.png)

**Comment by Spuner** [comment]
Yes, that's the problem. It's strange, since I don't change the volume... :-/

**Comment by Spuner** [comment]
I do not know whether it is necessary to create a new topic on this subject or not...

As I understand, it is possible to assign microphone on/off by a separate key combination (if you specify microphone in Alternative Audio Device). But the problem is that with these settings (on the screenshot), the sound is on and off together with the microphone, and if you link the chain, the microphone is on/off, but then the mute does not work.

Maybe there is some guide, how to properly configure it all, so that they are separate from each other? Or maybe two copies of Volume2 are possible to run...?

**Comment by irzyxa** [comment]
You should not use settings like you showed on screenshot. it locks all parameters of devices (volume and mute). Instead of that please use this one:
![image](https://user-images.githubusercontent.com/5119360/221404142-1234358c-9038-4dfc-b911-4d763291e899.png)

**Comment by Spuner** [comment]
It doesn't work, or I don't understand how... I'm already confused. It's confusing...

**Comment by irzyxa** [comment]
You can control two separate devices Main and alternative. So toy can go to Keyboards and set Mute On/Of for main device and Mute on/of (alternate device) for alternative device.
![image](https://user-images.githubusercontent.com/5119360/221404709-debba946-63e3-4076-8342-eef8b317a0ad.png)

**Comment by Spuner** [comment]
Я всё это уже делал. Я наверное всё испробовал, все варианты. Итог - мое [предыдущее сообщение](url=https://github.com/irzyxa/Volume2/issues/255#issuecomment-1445308869)

**Comment by irzyxa** [comment]
Show your settings.

**Comment by Spuner** [comment]
![2023-02-26 14_25_32-Volume² - Options](https://user-images.githubusercontent.com/30773815/221405034-d152322c-95a0-4ee1-b0b0-b045d42edd3b.png)

![2023-02-26 14_25_40-Volume² - Options](https://user-images.githubusercontent.com/30773815/221405040-9e91bf2e-8375-425f-b6cf-46fe9c07cb82.png)

Everything is the same as You showed in Your screenshots.

**Comment by irzyxa** [comment]
Can you change it using system setting:
![image](https://user-images.githubusercontent.com/5119360/221405158-aa4f1039-0fbd-49fd-ba4d-12f7df2f818b.png)

**Comment by Spuner** [comment]
I have a little different here, but I'm not quite sure what that gets me?

![2023-02-26 14_32_35-Greenshot](https://user-images.githubusercontent.com/30773815/221405313-30464082-6994-4ab0-b823-15d840e05de4.png)

Is it possible to run a second copy of Volume2 so that they work independently of each other?

**Comment by irzyxa** [comment]
All changes will be applied only after you press Apply button

**Comment by Spuner** [comment]
I think we don't fully understand each other :) Okay, it's okay... The important thing is that the main problem has been solved :)

P.S. If it is possible to run independently the second copy of Volume2, I will be glad.

**Comment by irzyxa** [comment]
Unfortunately it is not possible to have 2 copies of program running
