### ISSUE TITLE
Any way to show OSD of ModernFlyouts app?

### ISSUE THREAD

**Issue by FiftyFour7250** [irzyxa/Volume2#257]
I really love [ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts) OSD, it allows me to control Spotify and see all information while changing volume, but since I need to change volume of alternative device, which is not selected by default - I have to use Volume2. I configured VolumeUp and VolumeDown hotkeys, and ModernFlyouts OSD is no longer show when the volume changes, only for a pause(( Is there anything I can do? Really miss it.

![image](https://user-images.githubusercontent.com/78786088/222041622-2ed6b0d4-101e-4a85-bb43-a251550e25b0.png)

**Comment by irzyxa** [comment]
Just remove hotkeys that shown in the screenshot
![image](https://github.com/irzyxa/Volume2/assets/5119360/62109580-13ed-4b42-9cf9-ae5fead8396f)
