### ISSUE TITLE
Стандартный регулятор звука открывается с задержкой или вообще не открывается

### ISSUE THREAD

**Issue by sasgera** [irzyxa/Volume2#258]
Мне очень понравилась Ваша программа, но я обнаружил две ошибки:

1. При клике левой кнопкой мыши на значок индикатора в трее, стандартный регулятор звука открывается с задержкой ~1  сек или вообще не открывается.
Заметил, если навести указатель мыши на значок индикатора в трее, затем немного подождать и сделать клик - регулятор звука не открывается.
Но горячими клавишами стандартный регулятор звука открывается моментально.
я имею ввиду этот регулятор звука - см скрин
![tray_indicator](https://user-images.githubusercontent.com/126732946/222397149-6c36e049-80d3-4356-8985-66abac359478.jpg)

2. При перезагрузке/включении ПК, окно с настройками программы открывается с очень маленьким размером, вот скрин окна настроек 
![settings_Volume2_1_1_8](https://user-images.githubusercontent.com/126732946/222398298-7aabe8dc-26fd-4d37-99c9-f78ef98e4a61.PNG)

В настройках стоит галка "Запускать программу при загрузке ОС". Если закрыть программу, а потом вручную заново открыть, с размером окна настроек все норм.  

 - Windows version: [7 64bit]
 - Volume² version: [1.1.8, build 461]

Пожалуйста, посоветуйте что можно в этих случаях сделать.
Мой файл Config.ini [прикреплен](https://drive.google.com/uc?id=1p5Z1c4PsyhRqDHplev9JNbqk1muxOKoy&export=download)

**Comment by irzyxa** [comment]
For the first item please set Double click to No
![image](https://user-images.githubusercontent.com/5119360/222405742-66ab69ce-46fc-4304-a25a-db8a4359b22b.png)
The second one is an issue and I will try to fix it in the future.

**Comment by sasgera** [comment]
Александр, да, теперь регулятор звука открывается без задержки. Спасибо!

Чтобы окно с настройками открывалось с нормальными размерами, я сделал так:
- Снял "галку" Запускать программу при загрузке ОС
![system_settings](https://user-images.githubusercontent.com/126732946/222426948-06f53e34-d1c6-4c02-b09a-7b7567513674.jpg)

- В папку Автозагрузка добавил ярлык программы Volume2

![autoloading](https://user-images.githubusercontent.com/126732946/222427288-93b23fdf-05b6-4816-bebe-905b290b966a.jpg)
Теперь проблемы с размером окна настроек нет. 

У меня установлена "Setup" версия программы.
Хочу отметить, что в портативной версии программы, проблемы с размерами окна настроек нет.
Удачи Вам!
