### ISSUE TITLE
Icon step -1 and unusable when HiDPI and missing resolution

### ISSUE THREAD

**Issue by jimbo1qaz** [irzyxa/Volume2#26]
1.1.5 build 382, Windows 10 x64

My favorite system tray skin, DigitalBlue, as well as some other skins, have a recommended "volume speed" of -1. They do not load properly and fail to replace the previous systray icon. If Volume2 is restarted, the default icon (blue wedge) remains.

**Comment by jimbo1qaz** [comment]
I observed that this happens when HiDPI causes Volume2 to upscale the tray icon. I'm using 125% or 20px, and DigitalBlue apparently lacks 20px size. If I remember correctly, all other icons without 20px size were also step=-1 and unusable.

**Comment by irzyxa** [comment]
Fixed, version 1.1.5.385
