### ISSUE TITLE
Volume not in sync with actual system volume

### ISSUE THREAD

**Issue by chaoscreater** [irzyxa/Volume2#260]
- I have a mechanical keyboard with a volume control knob. I can use it to adjust the volume on my system. 
- I also have a smaller 4x3 macro keyboard and it too has a volume control knob.
- I also use an Authotkey script that allows me to control the volume by holding SHIFT + mouse wheel up/down.
- I also use the FN key + volume up/down on my laptop to control the volume

All 4 methods above allows me to control the volume on the system without issues. Whatever volume is currently set as (e.g 53%), all 4 of them will be able to take that volume level and adjust it. Perfect.

I came across Volume2 and I love that you can adjust the volume by scrolling the mouse wheel on the taskbar. It works fine, but I noticed that there's an issue. It doesn't seem to SET the system volume properly. For example, let's say the volume is at 53% at the moment. If I adjust it using Volume2, it'll go to e.g. 60%. BUT if I lower/increase the volume using my keyboard, it'll be lowered/increased based on the 53% instead of 60%. Again, all 4 methods that I was previously using works fine, it's just Volume2 that seems to be having issues.

Just to clarify, if the volume is currently at e.g. 53%, then Volume2 will be able to happily take that and adjust the volume up/down no problem. The volume DOES increase/decrease, i.e I can hear a different in the volume level. However, it doesn't seem to SET the volume value correctly, as other volume adjustment methods will still reference the 53% instead. I'm not sure what Volume2 is doing differently compared to how a mechanical keyboard volume knob adjusts volume.

Hope this makes sense. Here are my settings:

![image](https://user-images.githubusercontent.com/18227319/227833508-5c78dce1-9209-4d44-ac5a-bbe1f3d880fe.png)

![image](https://user-images.githubusercontent.com/18227319/227833545-eeaa3291-aa8c-457b-a868-89dabc2011d3.png)

**Comment by irzyxa** [comment]
It is not issue, Volume2 just works in this way, you can setup how many steps it takes from 0 to 100 %.
![image](https://user-images.githubusercontent.com/5119360/227856418-ebd334fd-d1e2-440a-a124-28da7a4a3e93.png)
If you want to Volume2 works like Windows controller, [please add hotkeys for Volume+/- keys](https://github.com/irzyxa/Volume2/wiki/FAQ#8-hide-windows-default-volume-osd)

**Comment by chaoscreater** [comment]
The volume changing spee

> It is not issue, Volume2 just works in this way, you can setup how many steps it takes from 0 to 100 %. ![image](https://user-images.githubusercontent.com/5119360/227856418-ebd334fd-d1e2-440a-a124-28da7a4a3e93.png) If you want to Volume2 works like Windows controller, [please add hotkeys for Volume+/- keys](https://github.com/irzyxa/Volume2/wiki/FAQ#8-hide-windows-default-volume-osd)

I don't think it's related to the volume changing speed? Let me try and give an example. 

Let's say the current volume is at **30%**.

- If I use FN + volume up just once on my laptop's built-in keyboard, volume will be at 33%. Current volume level is now at 33%.
- If I use the volume knob UP on my mechanical keyboard just once, volume will be at 36%. Current volume level is now at 36%.
- If I use the volume knob DOWN twice my 4x3 macro keyboard just once, volume will be at 30%. Current volume level is now at 30%.
- If I use Autohotkey script with SHIFT + mouse wheel up 4 times, volume will be at 42%. Current volume level is now at 42%.

So far, all the volume adjustment methods work fine. They all read from the current volume level and make adjustments based on that volume level. 

Now, here's the issue:
- Current volume level is at 42%. If I use any of the 4 methods to set the volume level down to e.g. 5%, then the current volume level is now at 5%.
- If I use mouse wheel up on my taskbar (Volume2 method), it will read the current volume level at 5% and make adjustments based on this volume level. Let's say I set the volume level to 60%. Current volume level **should be at 60%**.
- If I use mouse wheel down on my taskbar (Volume2 method), volume is now at 57%. Current volume level **should be at 57%**.
- If I use any of the 4 methods to decrease volume just once, expected volume level is 54%. However, the volume is at 2% instead. These 4 methods will still read the volume at 5%, instead of at 57%.

At this point, the volume changing speed / steps is not relevant here.

As for the hotkeys, that's using keyboard to adjust the volume if I understand it correctly. I only want to use the mouse wheel up/down on the taskbar to do this with Volume2.

**Comment by irzyxa** [comment]
Please show your Hotkeys tab

**Comment by irzyxa** [comment]
Okay, could you record short video and demonstrate an issue? 
I recommend you to set Volume speed to 50 (it is 2% like Windows has by default)

**Comment by chaoscreater** [comment]
Here you go.

https://user-images.githubusercontent.com/18227319/227867728-fe0f61ff-1fdd-4597-9cdf-fa328d19f5c2.mp4

**Comment by irzyxa** [comment]
So the issue is only with mechanical keyboard, correct? Other methods work correctly after Volume2?

**Comment by chaoscreater** [comment]
No.....the issue is purely with Volume2.

I don't know how to explain this better. Please read what I wrote here:
https://github.com/irzyxa/Volume2/issues/260#issuecomment-1484600416

**Comment by irzyxa** [comment]
Yes, I see. What does Windows volume mixer show?
![image](https://user-images.githubusercontent.com/5119360/227871978-503eeacd-6f6b-4a98-ae0c-5e317c40aa66.png)

**Comment by chaoscreater** [comment]
I've created another video, hopefully this time it shows the issue a bit clearer.
https://user-images.githubusercontent.com/18227319/227875899-b8b823e9-75dd-4977-a618-7363108cebd9.mp4

**Comment by irzyxa** [comment]
And one more case when you change volume from Windows mixer.

**Comment by chaoscreater** [comment]
Hmm interesting.

https://user-images.githubusercontent.com/18227319/227877916-53975c5a-4c41-40aa-8ae0-0ce6553475b5.mp4

**Comment by chaoscreater** [comment]
How would I set the key combination for e.g. Volume Up? I've tried to use the volume knob on my mechanical keyboard, but it doesn't register any key combination.

**Comment by irzyxa** [comment]
FN+VolumeUp/Down

**Comment by chaoscreater** [comment]
I did that. It didn't register the key combination. It simply just adjusted my volume up/down.

**Comment by irzyxa** [comment]
And what do you use form mechanical keyboard? What software?

**Comment by chaoscreater** [comment]
I use Keychron K3 at the moment. No software, it's all just native windows drivers.

**Comment by irzyxa** [comment]
Do you have any other software for control volume? Try to close all of them and configure hotkeys in Volume2.

**Comment by chaoscreater** [comment]
Hmm so I managed to set the keyboard hotkeys and tested again, same issue.

However, I think I know what's going on. I think perhaps my Autohotkey script is interfering with the volume. If I kill my Autohotkey scripts, then the volume adjustment with Volume2 (mouse wheel up/down on the taskbar) and then using my mechanical keyboard to adjust the volume will be fine, it'll read from the correct volume level. So looks like the issue is on my side, my apologies for this!

**Comment by irzyxa** [comment]
Frankly speaking, you could use only Volume2 for all your methods.
Shift + Mouse wheel
![image](https://user-images.githubusercontent.com/5119360/227883124-9ef494d4-5ce2-44c5-82ab-fdb5ff64910f.png)

**Comment by irzyxa** [comment]
What is  4x3 macro keyboard? Does it support OSC or MIDI?

**Comment by irzyxa** [comment]
They use their own software and drivers.

**Comment by chaoscreater** [comment]
Only to program the keys. Remember, those keys don't do anything unless you program them. The software they provide to you only programs the keys. There are no drivers to install and no apps to run in the background. Once you have programmed the keys, you can take it to a completely different PC and use it normally. The keyboard communicates to Windows using native windows drivers.
