### ISSUE TITLE
Add support for VOICEMEETER

### ISSUE THREAD

**Issue by irzyxa** [irzyxa/Volume2#264]
Hello,
after many years!
There is a solution to change volume of  VOICEMEETER POTATO?
I mean with mouse wheel as actually volume 2 do?
My computer has default device VOICEMEETER VAIO3
and to change volume the only solution i have found is 
Audio device: Altoparlanti Realtek
(see picture attached)

Motivation?
When i have several audio devices i cannot change global volume but with VOICEMEETER VAIO 3 yes, but it is not compatible as default device with Volume 2.
Thanks for your work.

![Volume2 Setting](https://user-images.githubusercontent.com/43314459/233410110-4f625491-ea7e-4208-9473-5e32937efa91.png)

_Originally posted by @donatopace in https://github.com/irzyxa/Volume2/discussions/250#discussioncomment-5675109_

**Comment by irzyxa** [comment]
@donatopace let's discus what should be done here and I would like to see your configuration. Could you record short video how you use Voicemeter?

**Comment by irzyxa** [comment]
What settings do you have here:
![image](https://user-images.githubusercontent.com/5119360/233851266-8cace4e5-01f7-4cc9-b59c-14495a5654c0.png)

**Comment by donatopace** [comment]
[image: image.png]

O need to change this
[image: image.png]


Il giorno dom 23 apr 2023 alle ore 18:13 Alexandr Irza <
***@***.***> ha scritto:

**Comment by irzyxa** [comment]
@donatopace please add images to GitHub and not email

**Comment by donatopace** [comment]
![Configuration VOICEMEETER](https://user-images.githubusercontent.com/43314459/233852941-d5f0c327-c902-4dca-9091-102d5f24e6bb.png)

I need change this Volume of Voicemeeter.
HOOK?

![HOOK of this Volume](https://user-images.githubusercontent.com/43314459/233852979-c0d70248-1d5f-407f-853b-64cf7807bb3c.png)

**Comment by donatopace** [comment]
Hello,
any news?
I want to buy these extra
Thanks.

**Comment by irzyxa** [comment]
It is not question related to money. I have to learn a new API, probably code a new library and only then try to implement feature in Volume2 project. And it is not my main project, it is pet project and I spend only couple of hours a week for it.

**Comment by donatopace** [comment]
ok,
how many months do you think it will take?
I would already like to thank you for the effort.

Can I send you another €30.00 immediately via PAYPAL?

Thank you.

**Comment by donatopace** [comment]
Hello,
i found API for Voicemeeter:
https://forum.vb-audio.com/viewtopic.php?f=8&t=346

**Comment by irzyxa** [comment]
@donatopace Yes, it is one of ways. I also found out that vban protocol can be used for this.
https://vb-audio.com/Voicemeeter/vban.htm

**Comment by irzyxa** [comment]
![image](https://github.com/irzyxa/Volume2/assets/5119360/c76b54d9-c317-4676-a517-582424f145d8)

**Comment by irzyxa** [comment]
@donatopace here is the first prototype:
https://drive.google.com/file/d/1Q8b0WMze1EmIdXO5VEjIE_0-hJPc8rtC/view?usp=sharing

**Comment by donatopace** [comment]
Wow,
you have made good job!
I have found only two little bug:
1) if i move volume slider on VAIO3 mixer is over 0dB and then use mouse
wheel on tray the volume go down to -60dB  immediately
if volume slider on VAIO3 mixer is 0dB or below all works well

2) Every time i change a value under "Volume2 options"
the icon on systray change and i need to change again on "OSD" to my
prefered value that is "tracktor Blue 16px 24px 32px"


I have made another donation to you

Il giorno mer 28 giu 2023 alle ore 19:03 Alexandr Irza <
***@***.***> ha scritto:

**Comment by irzyxa** [comment]
1) I still do not know if I should support values more than 0dB and how it can be used/implemented
2) I think it is bug from another feature. I will try to reproduce it and fix. But try to open theme settings (one of buttons in the left bottom corner) and see what settings you have there.

**Comment by donatopace** [comment]
Il giorno mer 28 giu 2023 alle ore 20:55 Alexandr Irza <
***@***.***> ha scritto:

**Comment by donatopace** [comment]
2. Solved with theme settings, thanks.

1. See image below


Il giorno mer 28 giu 2023 alle ore 20:55 Alexandr Irza <
***@***.***> ha scritto:

**Comment by irzyxa** [comment]
Please attach image on GitHub because it does not support images in email.

**Comment by donatopace** [comment]
![image](https://github.com/irzyxa/Volume2/assets/43314459/cf9c7112-30b7-4b5f-b51c-ca21ef1ed6e8)

**Comment by irzyxa** [comment]
Yes, I know because I use only value from 0 to 60, I think I will change it to use max value as 72 (60+12dB)

**Comment by donatopace** [comment]
You use value from: 
0dB     to    -60dB

now you can use max value to +12dB so:
12dB   to    -60dB

Now OSD volume is from:
0  to 100
You think it is a good idea if OSD volume range became:
0  to 120
and if i try to increase the value show 120 or other value
to indicate the user is over 0dB?

**Comment by irzyxa** [comment]
No, it will be -60 as 0 and +12 as 100%

**Comment by donatopace** [comment]
The risk is that the volume is over-boosted every-time because the users don nit know that 100% not is 0dB but +12dB

**Comment by irzyxa** [comment]
Okay, I have not found solution for 12dB but I updated version and fixed issue related to reset to zero(link the same as above)

**Comment by donatopace** [comment]
I think i have found solution for +12dB at volume 100% 
a "RED Little LETTER" or "RED Point" or what you prefer on the right of 100%

![Volume2 BOOST](https://github.com/irzyxa/Volume2/assets/43314459/30030373-d686-456f-ad68-c58beb394a79)



then when users reduce the volume a little

![Volume2 100](https://github.com/irzyxa/Volume2/assets/43314459/23f91463-0ff1-49a6-99ad-a2bb17843944)



Thanks.

**Comment by donatopace** [comment]
Basically there will be a step between +12dB and 0dB

**Comment by donatopace** [comment]
Hello,
i tried to download a new version with bug fixed but it still appears to be the old version.
Can you send me latest link?
Thanks.

**Comment by irzyxa** [comment]
No, becaue the latest version is the same that you tested. I needed to upload it because there was other changes for other tasks.

**Comment by Sundava** [comment]
Any way to also expand this feature to the `Hardware Out` devices ?
Currently adding a voicemeeter devices only goes from strip 1 to 8, which only correspond to inputs (Inputs in the voicemeeter sense)

I want to be able to change the volume sent to my headset without affecting the volume of the audio sent to OBS, for instance.  
(This is done by changing the volume of the first strip of `Hardware Out`, here -26dB in my screen)

![image](https://github.com/irzyxa/Volume2/assets/7022870/b98aa17a-1339-4670-bfcc-d021d10db529)

**Comment by irzyxa** [comment]
@Sundava Done. It is available in version [1.1.8.464](https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.464).

**Comment by irzyxa** [comment]
Probably it depends on Volume Speed option (Main tab). Please try to change it and look at volume value I think it will be different not -2 dB

**Comment by donatopace** [comment]
Hello,
i have change the Volume speed to max value (100 steps)
now when i scroll down from volume VAIO 3 for example +3dB
the first step down is   -0,6dB    and not from 0dB as expect as first value
you can try because i have tested on four  different computers

**Comment by donatopace** [comment]
I'll try to explain myself better.
when I lower the volume with the mouse wheel VAIO3 must jump to 0dB as the first value if it had values greater than 0dB while the first value always monitors 0dB

**Comment by donatopace** [comment]
So if VAIO3 has initial volume value of  +3dB   first step of mouse whell should be    0dB
actually is always -2dB     after i have changed the Volume speed to max value (100 steps)

**Comment by donatopace** [comment]
Have you been able to verify the problem?
Thank you

**Comment by donatopace** [comment]
Hello,
Have you been able to verify the problem?
Thank you

**Comment by irzyxa** [comment]
Sorry, I was busy. Yes, I reproduced it but I do not see ways to resolve it.
One possible solution is to show dB value on OSD
![image](https://github.com/irzyxa/Volume2/assets/5119360/047b77e0-aad9-4795-ac0d-99b940eddf4d)
