### ISSUE TITLE
keyboard fail

### ISSUE THREAD

**Issue by dearanswer** [irzyxa/Volume2#270]
add "Playback Devices" keyboard fail
add keyboard combination to 
press keyboard combination, "Playback Devices" do not show
This is a bug

**Comment by irzyxa** [comment]
It works for me. What is your system and program version?
![image](https://github.com/irzyxa/Volume2/assets/5119360/fa0cdab8-cbaa-451f-aece-7f2f66c980ff)

**Comment by dearanswer** [comment]
system version:win11 22h2 22621.1702
program version:1.1.8.461

**Comment by irzyxa** [comment]
Do you want to see the same window I showed?

**Comment by dearanswer** [comment]
sorry,I found the reason, I disabled the keyboard actions of Volume²
