### ISSUE TITLE
Limit default device options

### ISSUE THREAD

**Issue by jeffykle** [irzyxa/Volume2#272]
Is there any ways to limit which default devices can be cycled through using the "Set Next Default Device" action?

For example, I want to cycle only between headphones and speaker. I can disable the other devices in Windows but they often get automatically re-added if those devices get disconnected and reconnected, or another audio device is plugged in (display, headphones, bluetooth devices). I'd like to limit the software to only select from certain devices.
![image](https://github.com/irzyxa/Volume2/assets/37871091/17028ac4-c08f-4000-be6c-182f10195439)

**Comment by irzyxa** [comment]
Unfortunately it is not possible to configure, but I have an idea how it can be implemented:
![image](https://github.com/irzyxa/Volume2/assets/5119360/6f698e01-f085-4dde-80ed-4c3ab09798d7)

**Comment by irzyxa** [comment]
#297

**Comment by irzyxa** [comment]
It was implemented for feature #311
