### ISSUE TITLE
The Vol value of the system tray icon becomes abnormal when the wallpaper is changed.

### ISSUE THREAD

**Issue by fbi1967** [irzyxa/Volume2#274]
Version 1.1.8.463
The Vol value of the system tray icon becomes abnormal when the wallpaper is changed.

**Comment by irzyxa** [comment]
Any screenshots?

**Comment by fbi1967** [comment]
https://youtu.be/qZmqQQa5GGE

Version 1.1.8.461 is no problem.

**Comment by irzyxa** [comment]
The issue was reproduced and fixed. Will be available in the next build
