### ISSUE TITLE
Consent UI for administrative applications

### ISSUE THREAD

**Issue by nollinvoyd** [irzyxa/Volume2#275]
I just tried to get to the Volume2 settings by via my Volume2 debug shortcut, and my computer crashed.  The only thing I could access was my browser.  All taskbar items were frozen.  Couldn't get to my start menu or desktop.

A new, flashing Volume button appeared on my taskbar, with an icon that looked like the Windows Program Files directory icon, but it couldn't be closed.  

I did a ctrl-alt-del to open the task manager in order to end Volume2, but it did not help.  I went back to the task manager, and found an unfamiliar entry at the top, "Consent UI for administrative applications".  I ended that, and the problem went away.

This is the info from today's error log.  IO don't know why it would list Polish.lng there. 

7/17/2023 12:00:58 PM	ERROR	LoadLangList: Lang file Polish.lng The file being read is not a valid "Portable Network Graphics" image because it contains an invalid header. This file may be corrupted, try obtaining it again
7/17/2023 12:00:58 PM	DEBUG	LoadSettings succeeded
7/17/2023 12:00:58 PM	DEBUG	LoadLangList succeeded
7/17/2023 12:00:58 PM	DEBUG	LoadDevicesList succeeded
7/17/2023 12:00:59 PM	DEBUG	LoadVistaDevicesList succeeded
7/17/2023 12:00:59 PM	DEBUG	OpenSoundDevices succeeded
7/17/2023 12:00:59 PM	DEBUG	Set Mute Value succeeded
7/17/2023 12:01:03 PM	DEBUG	LoadSkinsList succeeded
7/17/2023 12:01:03 PM	DEBUG	LoadOSDSkinsList succeeded
7/17/2023 12:01:03 PM	DEBUG	LoadSoundsList succeeded
7/17/2023 12:01:03 PM	DEBUG	LoadSkinsToTray succeeded
7/17/2023 12:01:03 PM	DEBUG	LoadHotKeysInfo succeeded
7/17/2023 12:01:03 PM	DEBUG	RegHotKeys succeeded
7/17/2023 12:01:03 PM	DEBUG	SetKeyBoardHook succeeded
7/17/2023 12:01:03 PM	DEBUG	WTSRegisterSessionNotification Result = True
7/17/2023 12:01:03 PM	DEBUG	RegisterProtocol Result = True

**Comment by irzyxa** [comment]
Bug is related to Polish language was resolved in the latest version 1.1.8.463

**Comment by nollinvoyd** [comment]
Thanks
