### ISSUE TITLE
Volume2 don't show the correct volume

### ISSUE THREAD

**Issue by Dominiquini** [irzyxa/Volume2#276]
**Describe the bug**

The icon on the system tray don't show the correct volume when lower than 100! If I set it to 98, the Volume2 icon shows 96. If I set it to 88, Volume2 icon shows 76, etc...
The applications start working fine, but after a while, it starts presents this error! If I restart the application, or change some settings in the GUI, the error dissapears for a while, but come back after some time...

**Screenshots**
![Amgm5ER7MB](https://github.com/irzyxa/Volume2/assets/1180808/7a949503-69ad-454a-8396-c739608c3d08)
* Volume is set to 66, but tray icon shows 32!

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Volume² version: 1.1.8.463

**Additional context**
---

Thanks

**Comment by Dominiquini** [comment]
Testing here the version '1.1.8.461' appears to be working fine! This bug was introduced in the last update...

Thanks.

**Comment by irzyxa** [comment]
Fixed. [1.1.8.464](https://github.com/irzyxa/Volume2/releases/tag/v1.1.8.464)
