### ISSUE TITLE
Multiuser mode <-> Single mode installation bug

### ISSUE THREAD

**Issue by VenusGirl** [irzyxa/Volume2#279]
![Volume2 이미지 003](https://github.com/irzyxa/Volume2/assets/53147200/9d20bfc9-c432-4c8f-bfcc-0f0f92766103)

Unlike the title and description in install mode, the creation location of config.ini is reversed.

The description in Multiuser mode is reversed by the description in Single mode and the description in Single mode is reversed by the description in Multiuser mode.

There is a bug that installs in Multiuser mode in Single mode and installs in Multiuser mode in Single mode.

**Comment by irzyxa** [comment]
How do you test it?
I cannot approve this. After install in multi user mode I do not have Config.ini next to exe file.

**Comment by VenusGirl** [comment]
![Volume2 이미지 004](https://github.com/irzyxa/Volume2/assets/53147200/2dd922e8-10a6-4d29-ab00-f88d61adfb63)

The bug is that there is no Config.ini next to the exe file after installing in multi-user mode.
In multi-user mode, Config.ini must be created here and must work in common for all users.

Multi-user mode is for all users
Single user mode is the current user

Or

Multi-user mode is the current user
Single user mode is for all users

Which one is correct?

The former is correct in most installations.

**Comment by irzyxa** [comment]
There is correct description. If you have only one account on your PC and it has admins permissions you can use Single-user mode and settings will be stored in one place (next to exe files). If you have one PC and different accounts on it you should use Multi-user mode and settings will be stored for each user separately.

**Comment by VenusGirl** [comment]
OK!
I understand.
Therefore, I am attaching UserMode.adt as a newly modified Korean translation because users may be confused.
[UserMode.zip](https://github.com/irzyxa/Volume2/files/12164030/UserMode.zip)

**Comment by irzyxa** [comment]
Version 1.1.8.465 will contain these changes
