### ISSUE TITLE
Startup from scheduler (1.1.8.464)

### ISSUE THREAD

**Issue by 7OH** [irzyxa/Volume2#284]
**Describe the bug**
New verion create task in scheduler with parameter "/autorun", but not in a parameters section - in a program field.
In this case windows cannot find path.
Modifying those (move param to param section) solves problem.
But ater starting app - it recreate task with error again.

**Screenshots**
![vol2_464](https://github.com/irzyxa/Volume2/assets/3063507/91b8d41d-d83a-46ce-b08f-62a4420bd891)
must be
![vol2_464_2](https://github.com/irzyxa/Volume2/assets/3063507/8e4ac9e2-b0ec-47f2-9260-14a25e33c98a)

**Desktop (please complete the following information):**
 - Windows version: 11.22621.2070
 - Volume² version: 1.1.8.464

**Comment by irzyxa** [comment]
Fixed, version 1.1.8.465
