### ISSUE TITLE
Exception thrown after restart

### ISSUE THREAD

**Issue by LennZA** [irzyxa/Volume2#30]
Installed latest beta(build 397) with installer (Win10 x64). Application Error when trying to open after restarting machine.

http://i.imgur.com/zzNtDND.png

**Comment by irzyxa** [comment]
Maybe you don't have permissions to write to folder with Volume2. Do you use single or multiple user version?

**Comment by LennZA** [comment]
Single user, Administrator account.

**Comment by LennZA** [comment]
Reinstalled with MultiUser and works fine, also I didn't select the run as administrator option which I probably should have done.

**Comment by irzyxa** [comment]
Do you run it as Administrator? 
Volume2 settings - System - Run program as Administrator
