### ISSUE TITLE
Keyboard shortcut to switch between monitors doesn't work

### ISSUE THREAD

**Issue by slishnevsky** [irzyxa/Volume2#300]
**Describe the bug**

OK, maybe it is not a bug, but something else, not sure.

I defined a keyboard shortcut to switch to a secondary monitor (as displayed on attached screenshot), but it doesn't work.
When I press F1 (the bind key), nothing happens.

**Screenshots**

![126](https://github.com/irzyxa/Volume2/assets/2932739/9204b006-b603-42e0-8116-a59c450f0531)

Action: Run application
Keys combination: F1
Parameter: c:\Windows\System32\DisplaySwitch.exe /external

**Desktop (please complete the following information):**

 - Windows version: Windows 10 Pro (Version: 22H2, Build: 19045.3803)
 - Volume² version:  Version 1.1.8.465 (16.09.2023)

**I don't know why it doesn't work. Please advice.**

**One weird thing that I noticed:** DisplaySwitch.exe is exactly where it supposed to be. However, when I use Volume2 UI and click on that folder icon next to Parameter field to select DisplaySwitch.exe, I don't see it. I see in in File Explorer, but not through Volume2 UI.

Thank you.

**Comment by irzyxa** [comment]
@slishnevsky you can use another key combination or add F1 as lowlevel hotkey
![image](https://github.com/irzyxa/Volume2/assets/5119360/efb85639-d135-4119-b5cd-ffe436b0c419)
