### ISSUE TITLE
Active device no longer shows in osd

### ISSUE THREAD

**Issue by Loganicx** [irzyxa/Volume2#302]
Since installing the latest update, the osd don't show the active sound device in osd any more, but is stuck on the same sound device even if it's not the one being used. I've tried uninstalling and installing an older version but the problem still persist. 

![Screenshot 2024-01-05 172943](https://github.com/irzyxa/Volume2/assets/20395254/d35310a4-a6db-497a-9b42-78b61ebe5452)

**Desktop (please complete the following information):**
Windows 11 22H2
Volume² 1.1.8.465

Otherwise very happy for this software and thank you very much for it.

**Comment by irzyxa** [comment]
Could you record a short video? It is not clear for me.

**Comment by Loganicx** [comment]
> Could you record a short video? It is not clear for me.


https://github.com/irzyxa/Volume2/assets/20395254/8c12d11b-ff18-46ab-8522-601d68cb8202

Thank you very much for replying. I've recorded a small clip whereas you can see that when I change the active sound device, you can see it in the Win 11 volume settings, but the Volume2 OSD is stuck on the same device. Thank you again.

**Comment by irzyxa** [comment]
Okay, now I see what you mean. It is because you control only LOGITEC device (it is your main Audio Device) and it should be Windows default.

**Comment by Loganicx** [comment]
https://github.com/irzyxa/Volume2/assets/20395254/b6e5d427-cc8f-407f-a1ca-324f5a8495d7

Hi again. I've added another video. The osd just says Windows Default. Before it used to say the name of the device as well. Maybe I'm missing something here or some setting? Thanks again for your patience,

**Comment by irzyxa** [comment]
I think it is because you use Windows 10 OSD skin and should be Windows 10 v2
![image](https://github.com/irzyxa/Volume2/assets/5119360/42cdf323-5283-4f6b-bd1b-1ce959d3f72a)

**Comment by Loganicx** [comment]
Ahh, great! Now it works again. Thank you very much for your help. May I just ask. When I use this software on Windows 7, every time I change the default device with a hotkey, the osd will pop up as a good notification on which device it has changed to. That does not happen on Win 11. Is that something a setting that can be changed? 

![Screenshot 2024-01-05 224849](https://github.com/irzyxa/Volume2/assets/20395254/54621a79-2c9e-4a7a-a231-6f1b4d526a24)

**Comment by irzyxa** [comment]
![image](https://github.com/irzyxa/Volume2/assets/5119360/4cd9dc5b-1577-4f08-a939-8b1a41aa3678)
It works for me.

**Comment by Loganicx** [comment]
> ![image](https://private-user-images.githubusercontent.com/5119360/296613342-4cd9dc5b-1577-4f08-a939-8b1a41aa3678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzUwMjcsIm5iZiI6MTcwNTI3NDcyNywicGF0aCI6Ii81MTE5MzYwLzI5NjYxMzM0Mi00Y2Q5ZGM1Yi0xNTc3LTRmMDgtYTkzOS04YjFhNDFhYTM2NzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMjMyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2EyMmRlNGNlMmM1NTMwMGY0OWUzYWE0NGZkOGVkZWI0MGU1ZDkzMjE2OTdmZTFiNDdkZjA1ZmExNDViNDg3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gVjfFkJWSKl0xLd8wtiQVtkuKsgV00xCTsNU0wVB3M0) It works for me.

Is that the built-in windows popup message? Cause that works for me too, but it's so slow when browsing through so many audio devices. Your software used to popup the osd on sound device change before, at least it does on my win 7 machine :) Thanks for taking your time.

**Comment by irzyxa** [comment]
You should set NotifyVolumeType to 1 and in this case OSD will be used:
![image](https://github.com/irzyxa/Volume2/assets/5119360/686cf119-60bf-4698-b1e0-fefed2ed8316)

**Comment by Loganicx** [comment]
Thank you very much. Again great software, love it. Tried to donate via paypal but ended up buying from steam. Thanks again!
