### ISSUE TITLE
Settings window opens up every time I start windows

### ISSUE THREAD

**Issue by adrnjn** [irzyxa/Volume2#305]
**The main settings window opens up everytime I start windows , i cant find any settings to disable it, I have enabled it to run as a task instead of program but still nothing , what settings do i need to change?

![image](https://github.com/irzyxa/Volume2/assets/101308535/7533b827-e1f7-4334-90d1-c61be7e08c17)

 - Windows version: 10
 - Volume² version: [e.g. 1.1.8.465]

**Comment by irzyxa** [comment]
Here is possible solution:
https://github.com/irzyxa/Volume2/wiki/FAQ#12-settings-window-opens-up-every-time-program-starts
