### ISSUE TITLE
disable change volume by mouse wheel over task bar if sound is muted only by unmute with middle mouse botton.

### ISSUE THREAD

**Issue by Alexnoj** [irzyxa/Volume2#306]
disable change volume by mouse wheel over task bar if sound is muted only by unmute with middle mouse botton.

**Comment by irzyxa** [comment]
Please try to turn off option that shown in the screenshot below:
![image](https://github.com/user-attachments/assets/b481af9c-ee97-42c6-8f68-5afd9afb9865)

**Comment by Alexnoj** [comment]
Already found it. Thanks!
