### ISSUE TITLE
Mute All Microphones doesn't toggle back to unmute

### ISSUE THREAD

**Issue by balanced-RedJay** [irzyxa/Volume2#316]
**Describe the bug**
Assigning a key or mouse activation to Mute All Microphones works correctly to mute microphones system wide. However, subsequent re-activation of Mute All Microphones re-mutes instead of toggling the microphones back to unmuted. 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version: [e.g. 7, 8, 10(1909)]
    11 Pro, 22635
 - Volume² version: [e.g. 1.1.6.411]
     1.1.9.466
**Additional context**
I have tried with various microphone sources active with the same result
Re-muting is accompanied by the appearance of the Volume2 OSD mute symbol

**Comment by DrXadium** [comment]
I see this on Windows 11, Volume2 version 1.1.8.465

**Comment by irzyxa** [comment]
Because this action has name Mute All microphones and not On/Off or toggle. For toggle it is not clear how to detect what action should be applied on or off because we can have more than one microphone.

**Comment by balanced-RedJay** [comment]
@irzyxa Thanks, your explanation makes sense. I think the function would be more useful if it worked as a toggle like [this utility](https://github.com/iXab3r/MicSwitch), but I don't assume this is at all trivial to implement. 

There's similar built-in toggle mics functionality in Windows 11 using Win+Alt+K, but not all apps support it and that key pattern is inconveniently right-hand centric (I frequently have my right hand on the mouse). My workaround to both Vol2 and Windows mute mic feature limitations is now to use PowerToys to remap Win+Alt+K to a lefthand key combination.
