### ISSUE TITLE
Заморозка баланса на 50%?..

### ISSUE THREAD

**Issue by Gennady-G** [irzyxa/Volume2#317]
**irzyxa** привет!
Спасибо большое за прогу, пользуюсь больше 10 лет и ставлю всем..

У меня некритичный вопрос или пожелание - можно ли добавить какую-то функцию "ЗамОк на изменение баланса", чтобы залочить баланс посередине на 50%? Ну или может что посоветуете в моём случае:

есть нотник с колонками, и bluetooth наушники Panasonic RB-HF420B. Так вот иногда возникает ситуация когда после переключения выходного устройства (я не могу воспроизвести этот баг, он то есть то нет..) - скорее всего с наушников на колонки - играет только левая. то есть баланс переключается на 0%, и надо каждый раз лезть его возвращать в настройках. Подозреваю это происходит из-за того что BT наушники определяются как гарнитура с моно-сигналом, и потом при переключении обратно на колонки баланс устанавливается в ноль..

но не уверен. к сожалению не могу точно воспроизвести ситуацию когда это происходит.
и эта фигня кстати и на Win10 и на Win11..

![1-sound-2024-01-11_123142](https://github.com/irzyxa/Volume2/assets/5569346/9e1a76ba-9419-4b43-84eb-d376d955a52c)

![3-2024-02-04_002107](https://github.com/irzyxa/Volume2/assets/5569346/203c7d18-9373-42af-ba6c-6efc207ba2be)

![4-2024-02-07_181506](https://github.com/irzyxa/Volume2/assets/5569346/246fac45-0feb-4ca4-952b-bd7bde071b45)

![5-2024-02-07_181625](https://github.com/irzyxa/Volume2/assets/5569346/276ecad9-c83f-473d-ada5-b92bed49c640)

**update:** Кстати баланс восстанавливается - если в системной грокости (значок динамика справа внизу) - нажать мышкой и снизить бегунком громкость до нуля, и потом обратно увеличить. Тогда и права колонка начинает обратно играть.

**Comment by irzyxa** [comment]
I added some information for this similar issue #328.
![image](https://github.com/user-attachments/assets/7ac59af4-4b51-48d5-bae5-a50532cfef00)

**Comment by Gennady-G** [comment]
@irzyxa wow! Thank You much!) 👍
