### ISSUE TITLE
Control Method resets to Linear on every launch

### ISSUE THREAD

**Issue by AndrewEmets** [irzyxa/Volume2#318]
**Describe the bug**
The program doesn't seem to initialize the MethodControl property from the Config.ini file properly. On every launch, in the UI, the control method is set to be Linear, even though, on the previous launch I set it to be Logarithmic. The config file stores the correct value of 1 for the MethodControl variable

**Desktop**
 - Windows version: 11
 - Volume² version:  Version 1.1.9.466 (27.01.2024)

**Reproduce steps:**
• Launch app
• Set the Control Method to be Logarithmic/Table
• Close app
• Open the app again
• Observe the control method is reset back to linear

**Comment by irzyxa** [comment]
Unfortunately I cannot reproduce it, please record a short video.

**Comment by AndrewEmets** [comment]
https://github.com/irzyxa/Volume2/assets/1645093/8a2cba41-1715-4a5e-925c-27cbda27ddb5

Here's a short video. Let me know if I there are any useful logs that I can attach

**Comment by dogan-kara** [comment]
same here. it was set to "Logarithmic" as static. I had to change it to "Table" with every restart.

thanks @AndrewEmets for pointing this out. So I changed this only 1 to 2. Good to have a workaround 👍 
![image](https://github.com/user-attachments/assets/f55b4759-975d-4046-ab24-6d63162080fd)

Running as admin didn't effect the bug just fyi.
