### ISSUE TITLE
"Tooltip" option only showing "Windows Default" not changing.

### ISSUE THREAD

**Issue by srkdonpro** [irzyxa/Volume2#319]
I have updated Volume2 to v1.1.8.465, but the system tray Tooltip did not display the current device correctly; it remained stuck on "Windows Default." To provide more context, I configured it to "%V% %DF."

I have since rolled back to version 1.1.8.457, and now the tooltip accurately displays the device name as I switch my playback devices.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 Pro 22H2
 - Volume² version: v1.1.8.465

**Additional context**
N/A

**Comment by irzyxa** [comment]
Do you mean this option:
<img width="374" alt="image" src="https://github.com/irzyxa/Volume2/assets/5119360/6f972ac2-af84-473b-b0dc-6bc2e8526395">
Balloon is not supported from windows 8 and higher

**Comment by srkdonpro** [comment]
Oops! It seems I accidentally submitted an incomplete bug report earlier. I've now edited it, and it's ready for your review.
