### ISSUE TITLE
Alternate device

### ISSUE THREAD

**Issue by SkyTrax79** [irzyxa/Volume2#327]
Hi,

How would I configure the software to have for example scrolling on the taskbar to control the volume of the main device and on the top edge of the screen (whatever application is running) to control the alternate devices ?

Thanks a lot.

**Comment by irzyxa** [comment]
It it required to do not use keyboard at all?
Because you can use alternative device with Alt key.

**Comment by SkyTrax79** [comment]
Yes exactly, I meant without using the keyboard at all, ideally even without the mouse buttons, you scroll at the top it's the main device and you scroll at the bottom and it's the alternate one.  You can do it with the app Volumouse but I prefer yours for many things.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by irzyxa** [comment]
Here is a possible solution . Try to enable Screen edge option and add any application that is always run (chrome for example). In this case you can control alternative device on the top of screen and main device on taskbar.
