### ISSUE TITLE
Feature request:  Set default Windows audio volume on startup

### ISSUE THREAD

**Issue by mkanet** [irzyxa/Volume2#34]
Sound volume on Windows startup might sometimes be unpredictable (too loud, too low).

If possible, it would be great if Vol2 could set a preset volume for the default sound device when Vol2 starts up.  Vol2 would be the perfect utility to do this, if programmatically possible.

**Comment by irzyxa** [comment]
Try to create the task in Scheduler which will be ran after program start and set volume for selected device
