### ISSUE TITLE
wrong ico order in Standard.lsk skin

### ISSUE THREAD

**Issue by MaliusArth** [irzyxa/Volume2#37]
Volume2/Skins/Standard.lsk: names of the ico files are in wrong order.

Also, what format is .lsk? how can I make my own skin?

**Comment by irzyxa** [comment]
What version do you use?

11 нояб. 2017 г. 9:13 пользователь "MaliusArth" <notifications@github.com>
написал:

**Comment by MaliusArth** [comment]
1.1.4.347

**Comment by irzyxa** [comment]
Try to use the latest beta version 1.1.5
https://irzyxa.wordpress.com/downloads/


11 нояб. 2017 г. 9:17 пользователь "MaliusArth" <notifications@github.com>
написал:

**Comment by MaliusArth** [comment]
thanks
