### ISSUE TITLE
Standard.lsk skin icon behaves differently from default Win 7 icon

### ISSUE THREAD

**Issue by MaliusArth** [irzyxa/Volume2#38]
1.1.5.399
The original Win 7 volume icon shows the first icon if at 0 volume and the other 3 icons are evenly split across the range:
icon 1: 0%
icon 2: 1-32%
icon 3: 33-65%
icon 4: 66-100%
The Standard.lsk skin splits all 4 icons evenly.

**Comment by irzyxa** [comment]
Fixed. Version 1.1.6.420.
