### ISSUE TITLE
setting hotkeys doesn't detect Fn key

### ISSUE THREAD

**Issue by MaliusArth** [irzyxa/Volume2#40]
1.1.5.399
It's not possible to set a hotkey to "Fn + ..." eg. "Fn + F2" etc.

**Comment by irzyxa** [comment]
Fn keys do not generate any code,  so I can't catch them.  It is not
possible to do this.

11 нояб. 2017 г. 11:34 пользователь "MaliusArth" <notifications@github.com>
написал:
