### ISSUE TITLE
hotkey  for "Set Next Default Device" dosen't work

### ISSUE THREAD

**Issue by viscar** [irzyxa/Volume2#45]
I use Win + Num0 for "Set Next Defalut Device", and it doesn't work. OSD doesn't show up, and default device doesn't change.
But set the hot key to "Volume up", it works sell. So I think there is no hotkey conflict, the problem may be belongs to "Set Next Default Device" function.

By the wary, the same hotkey works on Volume2 v1.1.4.347, although the OSD doesn't show up too.
My OS is win10 64-bit.

**Comment by irzyxa** [comment]
What version do you use?
Latest version is 1.1.5.404
https://irzyxa.wordpress.com/downloads/
