### ISSUE TITLE
Keep settings on uninstall

### ISSUE THREAD

**Issue by jimbo1qaz** [irzyxa/Volume2#5]
every time I update version, I lose all previous settings. can you fix this?

**Comment by jimbo1qaz** [comment]
additional request: export and save settings?

**Comment by irzyxa** [comment]
Do you use installer? And what version you installing: Multi or Single user?

**Comment by jimbo1qaz** [comment]
beta version, multi-user with installer.

it automatically uninstalls old version for me. but I lose all settings when I reinstall. I think when uninstaller deletes registry entries, it removes settings.

installer "keep previous settings" for tray icon and OSD did nothing.

**Comment by irzyxa** [comment]
Fixed, version 1.1.5.360
For testing need to use new installer.

**Comment by jimbo1qaz** [comment]
I can't find 1.1.5.360. It's not on your website.

**Comment by irzyxa** [comment]
I know, this will be available on the next week
