### ISSUE TITLE
OSD very tiny

### ISSUE THREAD

**Issue by dizietsma** [irzyxa/Volume2#56]
Just upgraded to 1.1.6m the osd was tiny, so I downgraded but the tiny osd still remains, pic here:
![v2_osd](https://user-images.githubusercontent.com/3487065/46645833-b9e65d00-cb7e-11e8-9dc4-2bee94424906.jpg)
the osd is just off centre to the right between the task bar and the browser window:)

this happened on a work computer but there the osd, while still much reduced was still (barely) readable.

diziet

**Comment by irzyxa** [comment]
Try to use this instruction, it shows how to increase OSD size, but actions the same.
![unnamed](https://user-images.githubusercontent.com/5119360/46651914-38a4bf80-cbaa-11e8-8a9a-e0ff54526e63.gif)

**Comment by dizietsma** [comment]
Thankyou for the reply, very quick!  And works perfectly of course. :)

**Comment by audityx** [comment]
Hello!
What is the program which you created this screenshot gif animation contains mouse moving?
Thanks!

**Comment by irzyxa** [comment]
I think it was Photoshop.
