### ISSUE TITLE
Stops working after awhile (windows 10)

### ISSUE THREAD

**Issue by neetch1** [irzyxa/Volume2#59]
After awhile it doesnt detect that you wanna change volume but if clicking the hidden icon buttom right then it detects again.

Would be great to see a fix for this.

**Comment by neetch1** [comment]
btw volume changing still works for keyboard keys but stop working about every hour for scrolling on taskbar

**Comment by irzyxa** [comment]
Try to use option Restart hooks every ..., on tab System.

пн, 28 янв. 2019 г., 18:49 neetch notifications@github.com:

**Comment by neetch1** [comment]
thx trying it out

**Comment by neetch1** [comment]
thx think that worked. know if it will matter for performance if it restarts every 500ms?

**Comment by irzyxa** [comment]
You can increase this value for example to 5000 ms(5 seconds)
