### ISSUE TITLE
after switching Volume2 to admin. rights, it will not start more when booting Win-10 (build 1903)

### ISSUE THREAD

**Issue by s3n0** [irzyxa/Volume2#64]
Hello, 

when I set up administrator rights to run Volume2.exe it no longer starts when booting Windows system. I tried to move Volume2 to a system disk, but that didn't help. I have a Volume2 app on the "D:" hard drive.

I need Administrator rights for Volume2 because otherwise Volume2 does not work in some games or applications.

Finally, I was able to **solve** the problem with an alternative startup after change the value `ScheduleAutoRun=0` to `ScheduleAutoRun=1` in the `Config.ini` file.

**Volume2 ver.:** 1.1.6.411
**OS:** Windows-10, x64, build-1903

If necessary, I will add further info about the problem. 

By the way - great product this Volume2 !

**Comment by irzyxa** [comment]
https://github.com/irzyxa/Volume2/wiki/FAQ#3-autorun-does-not-work-on-windows-10
