### ISSUE TITLE
Volume2 spontneously shuts down.

### ISSUE THREAD

**Issue by nollinvoyd** [irzyxa/Volume2#65]
Volume² v1.1.6, build 411, Windows 1o Pro 1803

I was having a similar problem recently like those who reported Volume² not starting with windows.

I did a number of things, including a fresh OS reinstall, placing a shortcut into the startup folder, and creating a scheduled task to avoid the UAC.

I no longer have a problem with it opening at startup, but now I have what may or may not be a related issue.

I have it set to operate from the screen edge, '

![volume2](https://user-images.githubusercontent.com/20844322/60928837-ac701780-a263-11e9-943e-b3aabc21ebed.png)

but it randomly stops reacting to the mouse when I wheel scroll in those areas.  For a while it would close completely, but now it still displays in the systray, and I must must open the Volume² interface for the scroll bar to be reinstated.  I don't have to reset anything, only open the interface.

**Comment by irzyxa** [comment]
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

Alexandr Irza

________________________________

**Comment by nollinvoyd** [comment]
ok, thanks
