### ISSUE TITLE
How can I open app settings, if I set tray icon as None?

### ISSUE THREAD

**Issue by Rastishka** [irzyxa/Volume2#67]
Can you please add an option to Start menu like "Volume2 Settings?"

**Comment by irzyxa** [comment]
Run application from shortcut and if it has already started it shows Settings window.

Alexandr Irza

________________________________

**Comment by Rastishka** [comment]
I tried multiple times, but it shows settings window only if i click Right key → Run as Adminstrator on Win7.

Yesterday on Win10 was the same thing, but now is ok. Wierd thing....... 
May be it starts working after reboot?
