### ISSUE TITLE
Volume2 interface opens on Windows startup

### ISSUE THREAD

**Issue by nollinvoyd** [irzyxa/Volume2#68]
Volume² v1.1.6, build 413 (19.07.2019), Windows 1o Pro 1803

I made the chancgs that solved the last problem I posted about, and things were ok.
https://github.com/irzyxa/Volume2/wiki/FAQ#5-stops-working-after-awhile

I just did a fresh OS install.  I have Volume2 set to run at startup.  Everything works fine, except every time I boot up, the Volume2 interface opens.

Can you help me fix this?

thanks

**Comment by irzyxa** [comment]
You should remove copy of Volume2 from autorun (Task Manager - Startup)

**Comment by nollinvoyd** [comment]
Thanks
