### ISSUE TITLE
problem after displaying the OSD text of the active application

### ISSUE THREAD

**Issue by s3n0** [irzyxa/Volume2#69]
Hello. 

I use Volume2 to control the volume of the main sound card (CTRL + mouse wheel) and to control the current application (SHIFT + mouse wheel).

A small problem occurs when displaying OSD information. When I just changed the sound volume of an active application (SHIFT + mouse wheel) and then change the main volume of the sound card (CTRL + mouse wheel), the first time you turn the mouse wheel, the text of the active application and not the sound card is displayed. Only when the mouse wheel is turned a second time will the sound card volume text normally appear in the OSD.

So the problem (BUG) is only the name of the active application or audio device. The volume meter is displayed correctly as well as the sound volume percentage.

configuration:

Volume2 v1.1.6.412 (beta)
Windows 10 build 1903
OSD config style: Text

Detailed OSD settings - see attached screenshot:

![osd_config](https://user-images.githubusercontent.com/13181404/64067123-b25ef500-cc23-11e9-95af-9fc4e4dd3755.png)

![keyboard_config](https://user-images.githubusercontent.com/13181404/64067122-b1c65e80-cc23-11e9-9ded-ecf7814fcbd7.png)

**Comment by irzyxa** [comment]
Fixed. Will be available in the next version.
