### ISSUE TITLE
skins - disable fade-in delay

### ISSUE THREAD

**Issue by jimbo1qaz** [irzyxa/Volume2#7]
In beta versions, you gave each skin a different fade-in time. This makes them difficult to use because I can no longer instantly see the volume as I adjust it.

Can you add an option to disable fade-in for skins?

**Comment by irzyxa** [comment]
This option already exist
https://dl.dropboxusercontent.com/u/25826071/Pictures/OSD02.png

**Comment by jimbo1qaz** [comment]
ok that's good.

Do you think it would be a good idea to add a "edit settings" button, to 
reduce this kind of confusion?

**Comment by irzyxa** [comment]
Where it should be added? Can you illustrate an image, I think osd list doesn't have free space for button.

**Comment by jimbo1qaz** [comment]
Not sure, but I think a button's pretty important. The current UI doesn't give any indication that skins can be customized with fade-out settings.

Why is your settings panel non-resizable?
