### ISSUE TITLE
will not start unless run as administrator.  

### ISSUE THREAD

**Issue by davehue** [irzyxa/Volume2#70]
Been using V2 for a decade.  All of a sudden it won't load at windows startup.  Also when I click on the program file,  nothing happens.... unless I run as administrator.   Then, of course I have click to to get through the User Account Control screen.    But even if I set it up to always run as administrator it still won't load at startup.   There are no other users on my system.    I read the thread from earlier this year by a user with similar problem but I couldn't follow the solution.   
I've reinstalled a half a dozen times with different versions with the same result.  

Any help is appreciated.  I love this program.

**Comment by irzyxa** [comment]
You can look at question 3 here https://github.com/irzyxa/Volume2/wiki/FAQ

**Comment by davehue** [comment]
no I did not.  I've reinstalled it several times again.  It still refuses to load at startup

**Comment by irzyxa** [comment]
Did you read FAQ? You should change ini file, it will not be work without this.

**Comment by davehue** [comment]
got it.  Thank you.   got that one solved but I have another problem that has cropped up but I'll start a separate thread.
