### ISSUE TITLE
scroll on screen edge not working either max volume or mute 

### ISSUE THREAD

**Issue by davehue** [irzyxa/Volume2#73]
Using Chrome, (v2 version 1.1.6.410)    When using scroll method to change volume on the screen edge,  rolling the mouse wheel up or down either mutes the volume or takes it to the maximum.  there is no inbetween,  just one notch up and I'm getting blown out.  one notch down and it's muted.    If I click on the v2 icon in the notification area it begins to work normally,  but if I open a new tab the problem reappears. for that tab.    right now I have 4 tabs open.  two I've corrected (click on notification icon) and are working fine,  two tabs are not.     This is consistent and repeatable despite reinstalls and reboots.

**Comment by davehue** [comment]
Further information.   If,  within Tab A,  I click on the notification icon,  (as described above) v2 seems to work ok for that tab.  however, if I open another window and use it without clicking on the icon,  then go back to Tab A,  it malfunctions again requiring another click on the notification icon to render it usable.    this has rendered the screen edge volume change unusable which for me is the primary reason I like using v2.

**Comment by irzyxa** [comment]
Did you try option Reset hooks every 500 ms on tab System?

**Comment by davehue** [comment]
yes,  no effect

**Comment by davehue** [comment]
fixed it!   I had similar issues when using the mouse wheel to zoom in and out of google maps.   I had recently updated my mouse driver and with it the Logitech Smooth Scrolling extension.   removing the extension appears to have fixed it.  I'll keep monitoring over the next few days,  but I think that was it.
