### ISSUE TITLE
Request: Hide default windows volume OSD.

### ISSUE THREAD

**Issue by PINCHO93** [irzyxa/Volume2#79]
As the tittle says, option to remove default windows volume osd. I know HideVolumeOSD is out there, but would be nice to have it all in one program.

![image](https://user-images.githubusercontent.com/13229233/67908622-77723280-fb7c-11e9-9241-83f2308c051c.png)

**Comment by irzyxa** [comment]
When do you see it? Do you use a laptop?

**Comment by PINCHO93** [comment]
It's the osd that Windows shows on the top left corner of the screen for when you change the volume. Win 10 pro desktop pc.

**Comment by PINCHO93** [comment]
If you do a search for HideVolumeOSD you will see what I'm talkingabout, the code is open source if I'm right.

**Comment by irzyxa** [comment]
Where do you change volume? From Volume2?

**Comment by irzyxa** [comment]
Do you use keyboard with VolumeUp/Down/Mute keys?

**Comment by PINCHO93** [comment]
I use directly from my headset, keyboard and with Volume2 key binds. I'm on my way home from work, when I get on my pc I can try and display it better.

**Comment by PINCHO93** [comment]
So, this is what it would look like if I don't use HideVolumeOSD, and thisd is what my request is about. A way to hide the OSD within Volume2.

![2019-11-04_22-00-28](https://user-images.githubusercontent.com/13229233/68157776-a0187480-ff4e-11e9-8cf1-25242dfa0490.gif)

**Comment by irzyxa** [comment]
Add please highlighted shortcuts.
![image](https://user-images.githubusercontent.com/5119360/68159367-50d84100-ff5a-11e9-8674-de7794b5e1e0.png)

**Comment by PINCHO93** [comment]
Seems like that did it. Will test a bit more, and get back if something isn't right.

**Comment by PINCHO93** [comment]
Did a restart and it works fine. Thanks.
