### ISSUE TITLE
Volume2 icon stops changing randomly

### ISSUE THREAD

**Issue by jimbo1qaz** [irzyxa/Volume2#8]
Windows 7 x64 on Lenovo Y40-80 laptop, volume2 latest beta.

Volume2 stops updating its tray icon randomly (takes a few hours)

**Comment by irzyxa** [comment]
Changing the volume, working at this moment?

**Comment by jimbo1qaz** [comment]
did you update anything in the latest beta? the second-latest beta has this bug.

**Comment by irzyxa** [comment]
Please enable option Reload the hooks every 500 ms on tab System

**Comment by jimbo1qaz** [comment]
probably fixed with reload workaround.

what's the root cause of this bug?

**Comment by jimbo1qaz** [comment]
**Still broken** with "reload hook" enabled.
