### ISSUE TITLE
Volume2 not starting with windows 10

### ISSUE THREAD

**Issue by HackoDis** [irzyxa/Volume2#85]
I tried following the directions another person posted about volume 2 not running at startup on windows 10. I'm very confused as to how he fixed his issue. At windows 10 boot up, it won't start up i have to manually start it. It set to run as a admin and at start up. I really like this program, would love to get it running better.

**Comment by irzyxa** [comment]
https://github.com/irzyxa/Volume2/wiki/FAQ#3-autorun-does-not-work-on-windows-10

сб, 18 янв. 2020 г., 23:35 HackoDis <notifications@github.com>:
