### ISSUE TITLE
OSD skin bags

### ISSUE THREAD

**Issue by Dimmel77** [irzyxa/Volume2#90]
Hello! I Enjoyed the program of the tabernacle 6-7.No years after the test the latest version of the skin as it should stop working, there is no indication of the digital volume level, as if at the bottom show peaks gromkosti.Proveryal 2 PC, installed the new version over the old portable.
The skin can be repaired, I have become attached to it.
W-10 pro 1909

[ASUS OSD2.zip](https://github.com/irzyxa/Volume2/files/4534609/ASUS.OSD2.zip)

**Comment by irzyxa** [comment]
Please update the skin by this link https://github.com/irzyxa/Volume2/tree/master/OSD%20Skins/ASUS%20OSD2

**Comment by Dimmel77** [comment]
Many thanks! For the repair of the skin. All the best?
