### ISSUE TITLE
Skin setting changes don't apply

### ISSUE THREAD

**Issue by N3pp** [irzyxa/Volume2#92]
Any changes you make to the individual skins don't get applied or saved, you can see they're back to their default after you click apply then check their settings again. Presumably because of skin settings being stored in installation folder (`Program Files (x86)\Volume2` by default) and not in `AppData\Roaming\Volume2` like config.ini.

Because you can change them when you:

- install it somewhere else other than protected folders like Program Files.
- run it for the first time from the installer after the setup, because it makes it run with elevated privileges. Then whenever you open it manually after that or let it run at startup, it runs without admin rights.
- manually run it with elevated privileges (right click -> run as administrator).

Also because of the same reason, even if you select "same settings for all users" before installation and not "individual settings for all users", since it can't save config.ini to the default path, it falls back to `AppData\Roaming\Volume2` (not sure if I'm supposed to open a separate issue for this, thought I'd add it here since it seems to be very relevant).

**Comment by irzyxa** [comment]
But when you use installer you have possibility to change destination folder and set it to AppData\Roaming\Volume2. 
I think I can store user's settings to AppData\Roaming\Volume2\OSD Skins\<SkinName>\Skin.xml and these settings will not be erased when user will setup a new version.

**Comment by N3pp** [comment]
> But when you use installer you have possibility to change destination folder and set it to AppData\Roaming\Volume2.

Yeah but most users just install to the default path and they'll probably not gonna figure out why some of their settings don't apply/save. 

> I think I can store user's settings to AppData\Roaming\Volume2\OSD Skins<SkinName>\Skin.xml and these settings will not be erased when user will setup a new version.

That would be the most ideal.

**Comment by irzyxa** [comment]
Fixed. Version 1.1.6.420
