### ISSUE TITLE
Autorun fails when default sound device is disabled in Windows

### ISSUE THREAD

**Issue by kuznv** [irzyxa/Volume2#96]
Error log says:
Error:Sound no found!!!

**Desktop**
 - Windows version: 10
 - Volume² version: 1.1.6.419

**Additional context**
Tried, does not work:
AutoRun=0
ScheduleAutoRun=1

Works fine when launching the app manually
Works fine when default sound device is not disabled on boot

**Comment by irzyxa** [comment]
What behaviour do you expect?
I can try to implement running all the time but with icon in tray that shows default device is not available(for example red Volume2 logo)

**Comment by kuznv** [comment]
I expect it to work after I connect another sound device that isn't disabled. 
My use case: laptop with speakers that permanently disabled and headphones that I connect when I need to (not at boot). 
Separate logo isn't necessary, OSD is already telling you that device is disabled. 
But autorun fails, so OSD and hotkeys are not working. Even after you plug working sound device.

**Comment by irzyxa** [comment]
Please download a new version and if it is possible, test it.
https://drive.google.com/file/d/142NCmSZNDAF0xFIDU2PZdn2MI4wz_R-b/view?usp=sharing

**Comment by kuznv** [comment]
Thanks, it's fixed now. 
A small side effect: in previous version when you tried to adjust the volume using hotkeys, OSD told you that device is disabled (and you could still adjust the volume). Now when device is disabled, it ignores hotkeys and doesn't show OSD, only red icon in icon tray

**Comment by irzyxa** [comment]
I do not have device to control. You can select concrete device and not to use Default device.

**Comment by irzyxa** [comment]
Also I show red icon ONLY when PC does not have any active devices

**Comment by kuznv** [comment]
It used to say "Status: Off" on OSD. Now there's either just "Headphones" (no indication that they're disabled) when selecting concrete device or no OSD at all when using default.

**Comment by irzyxa** [comment]
Can you record a short video or show some screenshots?

**Comment by kuznv** [comment]
Hmm, it seems like "Status: off" only showing up after unplugging headphones. When that happens, selected sound device is blank in settings. 
![pic](https://user-images.githubusercontent.com/7094875/86359912-51a4ac80-bc7a-11ea-8324-e1f7537f1247.png)

**Comment by irzyxa** [comment]
It was a bug in version 419. You can download version 423 or use this one 425. What can I do more for this bug?

**Comment by kuznv** [comment]
Well, I liked that OSD indication that headphones are unplugged. I guess that was a good bug for me :)

**Comment by kuznv** [comment]
423 also has working OSD with unplugged headphones. Porting that on 425 would be great

**Comment by irzyxa** [comment]
No, I can not do this I do not know what default device is. I rewrote old code, so ti is not compatible with new.
