### ISSUE TITLE
Папка ярлыка для удаления программы

### ISSUE THREAD

**Issue by iDolmatov** [irzyxa/Volume2#98]
**Describe the bug**
Просьба проверить путь создания ярлыка в списке программ.
У меня он оказался "C:\Users\Dolma\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Volume2\Volume2 Uninstaller.lnk" (папка пользователя), а ярлык самой программы в списке всех программ.
**Screenshots**
![image](https://user-images.githubusercontent.com/19782385/85908083-172bb180-b82d-11ea-9b29-7bcd92c8f1fc.png)

**Desktop (please complete the following information):**
 - Windows version: 10 2004 19041.329
 - Volume² version: 1.1.6.423

**Additional context**
Размещение ярлыка для удаления в папке пользователя создаёт затруднения для удаления другим пользователем.

**Comment by irzyxa** [comment]
Fixed.
