### ISSUE TITLE
1.1.6.423 no longer works with Mouse - Mute (alt+left mouse button) for selected application.

### ISSUE THREAD

**Issue by huh02** [irzyxa/Volume2#99]
**Describe the bug**
1.1.6.419 works fine (Mute) with the game Wings of Destiny, I have set in the tab Mouse - Mute On / Off Alt + Left mouse button.
Audio device: Windows default.
I also have the game set up in Specified applications. It no longer works in version 1.1.6.423 with same settings. 
When I press a shortcut, nothing happens at all, nor any indicator.
Only when I turn on Alternative audio device: Windows default, this shortcut works, but mute "Speakers" instead of the application.
**Screenshots**
![419a](https://user-images.githubusercontent.com/51474439/86540484-07376000-bf06-11ea-827e-d95477760664.jpg)
![419b](https://user-images.githubusercontent.com/51474439/86540487-13bbb880-bf06-11ea-9f1f-43a22525a38f.jpg)
![419c](https://user-images.githubusercontent.com/51474439/86540491-19b19980-bf06-11ea-925e-ae872da96445.jpg)
![423a](https://user-images.githubusercontent.com/51474439/86540492-1cac8a00-bf06-11ea-9f9b-3a948ec1b5fc.jpg)
![423b](https://user-images.githubusercontent.com/51474439/86540494-1e764d80-bf06-11ea-90dc-0a1d2ff8177c.jpg)

**Desktop (please complete the following information):**
 - Windows version: 7 Pro Sp1
 - Volume² version: 1.1.6.423

**Additional context**

**Comment by irzyxa** [comment]
Can you try reproduce this bug on for example Chrome?

**Comment by huh02** [comment]
I'm not using Chrome, so I tried Winamp.
I copied the 419 and 423 folders to another name and changed the path to winamp.exe in 
Change volume for: Specified applications 
Both versions work with Winamp. When I returned the path back to wod.patched.exe, only version 419 works.
Something must have changed since version 419, version 423 is no longer able to control the game.
When I press alt + Left mouse button, nothing happens, the status window is not visible.
It works with Winamo.

**Comment by irzyxa** [comment]
Can you send me Errors.log file? ([Profile Folder](https://github.com/irzyxa/Volume2/wiki/FAQ#4-where-is-configini-located))

**Comment by huh02** [comment]
That will not be necessary. Errors.log contains only this recurring string:
ERROR	VolumeWorkApp: File contains no version information

**Comment by irzyxa** [comment]
Fixed. Will be available in version 1.1.6.426

**Comment by huh02** [comment]
Thanks!
